#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
#
# Generate the TLC configurations: `Shipped.cfg` (every mutation switch off --
# the tree as it stands) plus one `Mut_<Bug>.cfg` per switch. Each mutant lists
# the invariant it is expected to break FIRST, because TLC reports the first
# violated invariant and stops.
set -euo pipefail
cd "$(dirname "$0")"

BUGS=(BugResetGatesFirst BugCredBeforeRp BugTokenSurvivesPinChange
      BugSetPinKeepsPpuat BugChangePinKeepsPpuat BugStopUsingKeepsPerms
      BugNoConsumeAfterUp BugUnscopedCancel BugTouchNotSpent
      BugSoftLockLostOnWarmReset BugWarmResetReopensWindow
      BugCmWalkIgnoresChannel BugDeleteRpBeforeCred BugBackupSealedNotAGate)

# The invariant each mutant must break, so a silent mutant is visible as such.
target_inv() {
  case "$1" in
    BugResetGatesFirst)         echo ResetNeverWeakensSurvivingState ;;
    BugCredBeforeRp)            echo NoUnmanageableCredential ;;
    BugTokenSurvivesPinChange)  echo NoTokenAfterInvalidation ;;
    BugSetPinKeepsPpuat)        echo NoTokenAfterInvalidation ;;
    BugChangePinKeepsPpuat)     echo NoTokenAfterInvalidation ;;
    BugStopUsingKeepsPerms)     echo NoTokenAfterInvalidation ;;
    BugNoConsumeAfterUp)        echo NoAuthorizationBypass ;;
    BugUnscopedCancel)          echo NoCrossTransportTouchConsumption ;;
    BugTouchNotSpent)           echo NoCrossTransportTouchConsumption ;;
    BugSoftLockLostOnWarmReset) echo NoAuthorizationBypass ;;
    BugWarmResetReopensWindow)  echo NoAuthorizationBypass ;;
    BugCmWalkIgnoresChannel)    echo NoAuthorizationBypass ;;
    BugDeleteRpBeforeCred)      echo NoUnmanageableCredential ;;
    BugBackupSealedNotAGate)    echo ResetNeverWeakensSurvivingState ;;
  esac
}

ALL_INV=(NoAuthorizationBypass NoCrossTransportTouchConsumption
         NoTokenAfterInvalidation NoAccessibleSecretWithoutGate
         NoUnmanageableCredential ResetNeverWeakensSurvivingState)

emit() { # $1 = cfg, $2 = bug switch (""), $3 = sweep fix, $4 = ppuat fix
  local out=$1 on=${2:-} fix=${3:-TRUE} fix2=${4:-${3:-TRUE}}
  {
    echo "\\* Generated by formal/gen-configs.sh -- do not edit by hand."
    echo "SPECIFICATION Spec"
    echo "CONSTANTS"
    echo "    RPs = {\"r1\", \"r2\"}"
    echo "    Channels = {\"c1\", \"c2\"}"
    echo "    MaxRetries = 3"
    echo "    MismatchLimit = 2"
    echo "    MaxClock = 1"
    echo "    ResetWindow = 0"
    for b in "${BUGS[@]}"; do
      if [ "$b" = "$on" ]; then echo "    $b = TRUE"; else echo "    $b = FALSE"; fi
    done
    echo "    FixSweepDropsCredsBeforeRpEntries = $fix"
    echo "    FixPpuatRequiresPin = $fix2"
    echo "INVARIANTS"
    echo "    TypeOK"
    if [ -n "$on" ] && [ "${SOLO:-0}" = 1 ]; then
      # Solo: ONLY the invariant this mutant must break, so a mutant caught by
      # a sibling invariant cannot be mistaken for one that names its own.
      echo "    ${SOLO_INV:-$(target_inv "$on")}"
    elif [ -n "$on" ]; then
      local t; t=$(target_inv "$on"); echo "    $t"
      for i in "${ALL_INV[@]}"; do [ "$i" = "$t" ] || echo "    $i"; done
    else
      for i in "${ALL_INV[@]}"; do echo "    $i"; done
    fi
  } > "$out"
}

# The tree as it stands. Expected RED on NoUnmanageableCredential -- see the
# finding in formal/README.md; that is the result, not a broken model.
emit Shipped.cfg "" FALSE FALSE
# Each finding isolated, so neither can mask the other.
emit Shipped_OnlyFinding1.cfg "" FALSE TRUE
emit Shipped_OnlyFinding2.cfg "" TRUE FALSE
# The same tree with the proposed sweep ordering. Expected fully GREEN, and the
# baseline every mutant is measured against.
emit ShippedFixed.cfg "" TRUE TRUE
# Mutants carry the proposed fix so the pre-existing finding cannot mask them.
for b in "${BUGS[@]}"; do emit "Mut_$b.cfg" "$b" TRUE TRUE; done
# One config per mutant listing ONLY its target invariant.
for b in "${BUGS[@]}"; do SOLO=1 emit "Solo_$b.cfg" "$b" TRUE TRUE; done
# NoAccessibleSecretWithoutGate is the one invariant no switch names as its
# target. BugResetGatesFirst breaks it as well as its own, and this proves that
# solo -- previously a hand-written file wearing this script's header.
SOLO=1 SOLO_INV=NoAccessibleSecretWithoutGate \
  emit Solo_NoAccessibleSecretWithoutGate.cfg BugResetGatesFirst TRUE TRUE
echo "wrote Shipped.cfg, ShippedFixed.cfg and ${#BUGS[@]} mutant configs"
