#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
#
# Generate the TLC configurations: `Shipped.cfg` (every mutation switch off --
# the tree as it stands) plus one `Mut_<Bug>.cfg` per switch. Each mutant lists
# the invariant it is expected to break FIRST, because TLC reports the first
# violated invariant and stops.
set -euo pipefail
cd "$(dirname "$0")"

BUGS=(BugResetGatesFirst BugCredBeforeRp BugTokenSurvivesPinChange
      BugSetPinKeepsPpuat BugChangePinKeepsPpuat BugStopUsingKeepsPerms
      BugNoConsumeAfterUp BugUnscopedCancel BugTouchNotSpent
      BugSoftLockLostOnWarmReset BugWarmResetReopensWindow
      BugCmWalkIgnoresChannel BugDeleteRpBeforeCred BugBackupSealedNotAGate
      BugConsumeKeepsMcGa BugNoDropStaleCancelAtEntry BugWrongPinKeepsToken
      BugSeedDoesNotLead)

# Mutants whose defect the shipped seed-lead makes unreachable: they rebuild a
# pre-0x08BF ordering bug, so their configuration must be the pre-0x08BF tree.
# That the list is not empty is the measured strength of that fix -- see README.
companion_bug() {
  case "$1" in
    BugBackupSealedNotAGate) echo BugSeedDoesNotLead ;;
    *) echo "" ;;
  esac
}

# The invariant each mutant must break, so a silent mutant is visible as such.
target_inv() {
  case "$1" in
    BugResetGatesFirst)         echo ResetNeverWeakensSurvivingState ;;
    BugCredBeforeRp)            echo NoUnmanageableCredential ;;
    BugTokenSurvivesPinChange)  echo NoTokenAfterInvalidation ;;
    BugSetPinKeepsPpuat)        echo NoTokenAfterInvalidation ;;
    BugChangePinKeepsPpuat)     echo NoTokenAfterInvalidation ;;
    BugStopUsingKeepsPerms)     echo NoTokenAfterInvalidation ;;
    BugNoConsumeAfterUp)        echo NoAuthorizationBypass ;;
    BugUnscopedCancel)          echo NoCrossTransportTouchConsumption ;;
    BugTouchNotSpent)           echo NoCrossTransportTouchConsumption ;;
    BugSoftLockLostOnWarmReset) echo NoAuthorizationBypass ;;
    BugWarmResetReopensWindow)  echo NoAuthorizationBypass ;;
    BugCmWalkIgnoresChannel)    echo NoAuthorizationBypass ;;
    BugDeleteRpBeforeCred)      echo NoUnmanageableCredential ;;
    BugBackupSealedNotAGate)    echo ResetNeverWeakensSurvivingState ;;
    BugConsumeKeepsMcGa)        echo NoAuthorizationBypass ;;
    BugNoDropStaleCancelAtEntry) echo NoCrossTransportTouchConsumption ;;
    BugWrongPinKeepsToken)      echo NoTokenAfterInvalidation ;;
    BugSeedDoesNotLead)         echo NoUnmanageableCredential ;;
  esac
}

ALL_INV=(NoAuthorizationBypass NoCrossTransportTouchConsumption
         NoTokenAfterInvalidation NoAccessibleSecretWithoutGate
         NoUnmanageableCredential ResetNeverWeakensSurvivingState)

emit() { # $1 = cfg, $2 = bug switch (""), $3 = sweep fix, $4 = ppuat fix
  local out=$1 on=${2:-} fix=${3:-TRUE} fix2=${4:-${3:-TRUE}}
  {
    echo "\\* Generated by formal/gen-configs.sh -- do not edit by hand."
    echo "SPECIFICATION Spec"
    echo "CONSTANTS"
    echo "    RPs = {\"r1\", \"r2\"}"
    echo "    Channels = {\"c1\", \"c2\"}"
    echo "    MaxRetries = 3"
    echo "    MismatchLimit = 2"
    echo "    MaxClock = 1"
    echo "    ResetWindow = 0"
    for b in "${BUGS[@]}"; do
      if [ "$b" = "$on" ] || { [ -n "$on" ] && [ "$b" = "$(companion_bug "$on")" ]; }
      then echo "    $b = TRUE"; else echo "    $b = FALSE"; fi
    done
    echo "    FixSweepDropsCredsBeforeRpEntries = $fix"
    echo "    FixPpuatRequiresPin = $fix2"
    echo "INVARIANTS"
    echo "    TypeOK"
    if [ -n "$on" ] && [ "${SOLO:-0}" = 1 ]; then
      # Solo: ONLY the invariant this mutant must break, so a mutant caught by
      # a sibling invariant cannot be mistaken for one that names its own.
      echo "    ${SOLO_INV:-$(target_inv "$on")}"
    elif [ -n "$on" ]; then
      local t; t=$(target_inv "$on"); echo "    $t"
      for i in "${ALL_INV[@]}"; do [ "$i" = "$t" ] || echo "    $i"; done
    else
      for i in "${ALL_INV[@]}"; do echo "    $i"; done
    fi
  } > "$out"
}

# THE TREE AS IT STANDS, and it is the green baseline the mutants are measured
# against. Two constants carry the history: `FixPpuatRequiresPin` shipped
# verbatim at 0x08C0, so it is ON; `FixSweepDropsCredsBeforeRpEntries` is a
# counterfactual the tree did NOT take -- 0x08BF made the seed lead the wipe
# instead, which is the default (`BugSeedDoesNotLead = FALSE`), so it is OFF.
emit Shipped.cfg "" FALSE TRUE
# The two findings this model produced, kept as regression configurations rather
# than deleted: each is the tree with exactly the shipped fix taken back out.
emit Historical_E76.cfg BugSeedDoesNotLead FALSE TRUE
emit Historical_E77.cfg "" FALSE FALSE
# Mutants run on the tree's own settings, so nothing pre-existing can mask them.
for b in "${BUGS[@]}"; do emit "Mut_$b.cfg" "$b" FALSE TRUE; done
# One config per mutant listing ONLY its target invariant.
for b in "${BUGS[@]}"; do SOLO=1 emit "Solo_$b.cfg" "$b" FALSE TRUE; done
# NoAccessibleSecretWithoutGate is the one invariant no switch names as its
# target. BugResetGatesFirst breaks it as well as its own, and this proves that
# solo -- previously a hand-written file wearing this script's header.
SOLO=1 SOLO_INV=NoAccessibleSecretWithoutGate \
  emit Solo_NoAccessibleSecretWithoutGate.cfg BugResetGatesFirst FALSE TRUE
echo "wrote Shipped.cfg, 2 historical configs and ${#BUGS[@]} mutant configs"
