----------------------------- MODULE TraceSeams -----------------------------
(*****************************************************************************)
(* SPDX-License-Identifier: AGPL-3.0-only                                    *)
(* Copyright (C) 2026 RS-Key contributors                                    *)
(*                                                                           *)
(* PHASE 4 -- TRACE VALIDATION: replay a RECORDED emulator session against   *)
(* RSKeyAppletSeams and require the model to admit every step. The trace     *)
(* (TraceSeamsData, generated by scripts/trace_map.py from a live            *)
(* `tools/emu` run) is forced step by step: `TraceNext` at position `idx`    *)
(* takes exactly the recorded action, so the whole behavior space is the one *)
(* linear run -- and a step the model refuses leaves NO successor, which TLC *)
(* reports as a deadlock AT THAT STEP. GREEN therefore means "this real      *)
(* session is a behavior of the model"; the model's own invariants are       *)
(* checked along the way, so a recorded session that drove the model into a  *)
(* violation would be RED with the step visible.                             *)
(*                                                                           *)
(* This is the empirical half of fidelity, complementing the mutants: the    *)
(* Bug* matrix proves the model CAN catch defects, the citations say which   *)
(* code each action claims to abstract, and this measures that the code as   *)
(* it RUNS stays inside the model's behaviors -- on the sessions recorded.   *)
(* A trace is evidence about itself, not a proof: coverage grows by          *)
(* recording richer sessions, and the recorded roster is listed in           *)
(* formal/traces/.                                                           *)
(*                                                                           *)
(* The falsifiability half lives in TraceSeamsBad.tla: a hand-written trace  *)
(* the model must REFUSE, and floors.txt requires that row RED -- a replay   *)
(* harness nobody has watched reject anything asserts nothing. The two       *)
(* modules duplicate this small harness because EXTENDS cannot be            *)
(* parameterized by a configuration; keep them in lockstep.                  *)
(*****************************************************************************)
EXTENDS RSKeyAppletSeams, Sequences, TraceSeamsData

VARIABLE idx
tvars == << sel, held, fresh, pfresh, oneShotSig, psig, oathCodeSet,
            refused, viol, idx >>

TraceInit == Init /\ idx = 1

\* The recorded action at `e`, as the model action it maps to. The CASE is
\* total over what scripts/trace_map.py emits; an unknown `act` fails the
\* evaluation loudly rather than stuttering past it.
Event(e) ==
    CASE e.act = "SelectOther" -> SelectOther(e.a)
      [] e.act = "Reselect"    -> Reselect(e.a)
      [] e.act = "PivVerify"   -> PivVerify(e.ok)
      [] e.act = "PgpVerify"   -> PgpVerify(e.r, e.ok)
      [] e.act = "PivKeyOp"    -> PivKeyOp
      [] e.act = "CardReset"   -> CardReset
      [] e.act = "PowerCycle"  -> PowerCycle

TraceNext ==
    \/ /\ idx <= Len(Trace)
       /\ Event(Trace[idx])
       /\ idx' = idx + 1
    \/ /\ idx > Len(Trace)
       /\ UNCHANGED tvars

TraceSpec == TraceInit /\ [][TraceNext]_tvars

=============================================================================
