---- MODULE TraceSeamsData ----
(*****************************************************************************)
(* SPDX-License-Identifier: AGPL-3.0-only                                    *)
(* Copyright (C) 2026 RS-Key contributors                                    *)
(*                                                                           *)
(* GENERATED by scripts/trace_map.py from formal/traces/seams-session.jsonl  *)
(* -- do not edit by hand; `python3 scripts/trace_map.py --write` remaps.    *)
(*****************************************************************************)

Trace == <<
    [act |-> "SelectOther", a |-> "piv"],
    [act |-> "PivVerify", ok |-> FALSE],
    [act |-> "PivVerify", ok |-> TRUE],
    [act |-> "SelectOther", a |-> "oath"],
    [act |-> "SelectOther", a |-> "piv"],
    [act |-> "Reselect", a |-> "piv"],
    [act |-> "SelectOther", a |-> "pgp"],
    [act |-> "PgpVerify", r |-> "pw1", ok |-> TRUE],
    [act |-> "PgpVerify", r |-> "pw3", ok |-> FALSE],
    [act |-> "CardReset"],
    [act |-> "SelectOther", a |-> "piv"],
    [act |-> "PowerCycle"],
    [act |-> "SelectOther", a |-> "pgp"]
>>

====
