#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
"""Write the scope table from the bundles, and refuse one written beside them.

Stage 4's exit asks that the scope table "explain what exactly remains bounded,
and that its content be DERIVED from the slice's bundle rather than written in
parallel to it". It was written in parallel to it. `docs/authorization-slice.md`
carried fourteen hand-typed rows under `## The bounds`, `grep -rn
"authorization-slice" scripts/*.py` found no reader, and six mutations were
driven across eight gates at exit 0 on every one: a docs row's Kani sequence
bound 5 -> 9999 while the bundle still said 5, a docs row's `model Channels 2`
-> 77 while the `.cfg` still assigned 2, the BUNDLE's `bound_sequence` 5 -> 9999
and `bound_channels` 2 -> 77 while the docs still said 5 and 2, a docs row
renamed after a constant that does not exist, and a whole docs row deleted.

The bundles already carry the numbers as structured data — 541 `bound_*` keys
over 107 `[[method]]` rows in 17 files — and `bundle_gate.method_bounds` floors
them, but on COUNT and TYPE only: the VALUES are unconstrained and nothing
rendered them anywhere. So this writes them out, the shape `evidence_gate.py`
already uses on `docs/assurance-vector.md`: one page, `--write`, a byte diff, a
`check.sh` row.

## What it renders, and why all seventeen

All seventeen bundles, not `SEC-FIDO-001`'s alone. The criterion says "the
slice's bundle" because there was one bundle when it was written; there are
seventeen now — `SEC-FIDO-006` having since split into three clause bundles and
the six `SEC-STORE-*` having landed — and rendering one would leave 508 of the
541 bounds unshown, the criterion answered for a sixteenth of the evidence, which
is the shape it exists to refuse. Measured: all seventeen are `p0-launch` rows of
`assurance/configurations.toml`, so "all the bundles" and "the P0-launch rows
carrying any raw evidence" are one set, and so is the tranche itself — 0 of its
17 rows are without a bundle. That difference is DERIVED on the page from the
ledger rather than listed here — a hand-typed list of ids on a generated page is
the defect one paragraph up.

## The column the number travels with

`shipped_relation` is the bundle's per-ROW prose and is required of every method
row. The consequence a scope table is for — *what stops being proved* — is
per-BOUND, so it is carried the same way one field down: `stops_<name>` beside
`bound_<name>`. All 541 carry one now; the page prints that as a number rather
than asserting it, and a cell reading `—` would be a bound whose consequence
lives only in its row's `shipped_relation`, printed under the table. The count is
the measurement either way — the page read `0 of 292` before the field existed.

The rules the field earns are the ones that can fire before it is adopted: a
`stops_*` with no `bound_*` twin is a consequence attached to nothing, a
`stops_*` occupied by a non-answer is the field dropped in a spelling the roster
cannot see, and a bundle that carries the field for SOME of its bounds is
half-adopted — which is how a column comes to look complete while most of it is
the fallback.

## The parallel table

Deleting the hand-written rows is not enough on its own: nothing would stop the
next one being typed, on this page or another. So [`no_parallel_table`] holds two
directions — the slice page's own `## The bounds` section carries no table at
all and points here, and this page's table header occurs in no other tracked
markdown. The second is the completeness half, and it is the half every guard in
this tree has failed.

Deliberately not here: whether a bound's VALUE is the right one. Nothing can say
that a sequence of 5 is enough. What this keeps honest is that the number a
reader sees is the number the evidence was taken at, that every one of them is
shown rather than a chosen fourteen, and that a consequence column cannot be
edited away from the measurement it describes.
"""

import pathlib
import re
import sys
import tomllib

import bundle_gate
import claims_gate

ROOT = pathlib.Path(__file__).resolve().parents[1]

BUNDLES = pathlib.Path("assurance/bundle")
ARTIFACT = pathlib.Path("docs/assurance-bounds.md")
SLICE = pathlib.Path("docs/authorization-slice.md")
LEDGER = pathlib.Path("assurance/configurations.toml")
CHECK = pathlib.Path("scripts/check.sh")

GENERATED_BY = "Generated by scripts/bounds_gate.py --write"

#: The prefix `bundle_gate.REQUIRED` already spells as `bound_*`, and the one
#: this file adds beside it. Both are read as prefixes of a NAME: `bound_` on its
#: own is the wildcard rather than a key, which `bundle_gate.method_bounds`
#: refuses and this skips for the same reason.
BOUND, STOPS = "bound_", "stops_"

#: The slice page's section, and the table header this page owns. Both are
#: literals because both are what a hand would retype: the section is where the
#: parallel table stood, and the header is the shape it would come back as.
SECTION = "## The bounds"
#: The tranche whose rows a bundle is written for. `matrix_gate.py` owns the
#: vocabulary; this names the one row set the page's denominator is about.
LAUNCH = "p0-launch"
TABLE_HEADER = "| Bound | Value | What stops being proved |"

#: Floors, at the measured counts of this tree: 17 bundles, 107 method rows
#: carrying at least one bound, 541 bounds, and **all 541** of those carrying the
#: per-bound consequence. Moved from 8/61/295/295 the day `SEC-FIDO-006` was
#: split into `SEC-FIDO-006A/B/C` and the three clause bundles landed, and from
#: 11/83/397/397 the day the six `SEC-STORE-*` bundles landed — which is the whole
#: `p0-launch` tranche carrying a bundle for the first time, so the denominator
#: this page is about and the set of bundles it renders became the same 17. Each
#: new value was READ OFF `table()` over the seventeen bundles rather than added
#: up from the deltas, which each reported the count as of the moment it was
#: written and so could only be a lower bound on the merge.
#:
#: Each is the DEFAULT of an [`audit`] parameter and is
#: read once, at import — so a case reaches it by passing a value, and
#: monkeypatching the name here changes nothing about what `main` runs. That is
#: `claims_gate.DISCLAIMER_FLOOR`'s shape and it is deliberate: a ceiling a case
#: patches down is a ceiling whose shipped value is never checked, which this
#: tree has measured. `PROSE_FLOOR` was 0 while the column was empty, and inert
#: by construction because nothing can be under it; at the count it is the ratchet
#: the other three are — dropping one `stops_*` is red until an author moves it in
#: the same diff, which is the direction a floor exists for.
BUNDLE_FLOOR = 17
ROW_FLOOR = 107
BOUNDS_FLOOR = 541
PROSE_FLOOR = 541

#: A rendered bound row, for the completeness rule. It reads the page ON DISK
#: rather than the string `render` just built, so a filter inside `render` and a
#: hand edit to the file are both a finding — the byte diff sees the second and
#: would agree with the first.
BOUND_ROW = re.compile(r"^\| `bound_[a-z0-9_]+` \|", re.M)


def bundles(root, findings):
    """Every bundle, parsed, in roster order. Reuses `bundle_gate`'s roster.

    A bundle with no `property.id` is reported and skipped: every bound below is
    attributed to a property, and a nameless one would be rendered under a `?`
    that reads like a property rather than like a hole. Unparseable TOML is
    reported too rather than raised — `bundle_gate.py` is the row that owns a
    malformed bundle, and this one going down with a traceback beside it says
    less than one line naming the file.

    Read ONCE per audit and handed to both readers below. The first version
    called this from each of them, so a nameless bundle was reported twice in one
    run — a rule firing as many times as it has callers is a count nobody can
    read.
    """
    out = []
    for rel in bundle_gate.bundles(root):
        try:
            doc = tomllib.loads((root / rel).read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError) as error:
            findings.append(f"{rel}: cannot be read as a bundle: {error}")
            continue
        pid = str(doc.get("property", {}).get("id", "")).strip()
        if not pid:
            findings.append(
                f"{rel}: a bundle with no property id — every bound it carries"
                " would be attributed to nothing"
            )
            continue
        out.append((rel, pid, doc))
    return out


def rows(doc):
    """(index, the method row) for every `[[method]]`, one-based as the file reads."""
    return [
        (index, row)
        for index, row in enumerate(doc.get("method", []), 1)
        if isinstance(row, dict)
    ]


def bounds_of(row):
    """The bounds of one method row, in the order the bundle writes them.

    `bound_` alone is the prefix and not a name — `bundle_gate` refuses it there
    and this drops it here, so the two agree about what a bound IS rather than
    each deciding.
    """
    return [key for key in row if key.startswith(BOUND) and key != BOUND]


def table(parsed):
    """Every bound of every bundle, attributed. The whole derivation.

    One record per `bound_*` key: which bundle, which property, which method row
    (its index, obligation, method word and artifact), the bound's name and
    value, and the consequence — `stops_<name>` when the bundle carries it, and
    `None` when it does not, so the renderer can print the shortfall rather than
    paper over it.
    """
    out = []
    for rel, pid, doc in parsed:
        invariant = str(doc.get("property", {}).get("invariant", "")).strip()
        for index, row in rows(doc):
            found = bounds_of(row)
            for key in found:
                name = key[len(BOUND) :]
                out.append(
                    {
                        "bundle": str(rel),
                        "property": pid,
                        "invariant": invariant,
                        "index": index,
                        "obligation": str(row.get("obligation", "")).strip(),
                        "method": str(row.get("method", "")).strip(),
                        "artifact": str(row.get("artifact", "")).strip(),
                        "cfg": str(row.get("cfg", "")).strip(),
                        "features": str(row.get("features", "")).strip(),
                        "relation": str(row.get("shipped_relation", "")).strip(),
                        "bound": name,
                        "value": row[key],
                        "stops": row.get(f"{STOPS}{name}"),
                    }
                )
    return out


def launch_tranche(root):
    """The P0-launch ids, from the ledger that owns which rows those are.

    Read rather than listed, because a page saying "the three rows without a
    bundle are 006A, 006B and 006C" is a hand-written list of ids on a generated
    page, which is the defect one paragraph up. `matrix_gate.py` owns the tranche
    vocabulary; this asks the ledger for one name and derives the difference.
    """
    path = root / LEDGER
    if not path.is_file():
        return []
    doc = tomllib.loads(path.read_text(encoding="utf-8"))
    return sorted(doc.get("tranche", {}).get(LAUNCH, []))


def check_consequences(parsed, findings):
    """The three rules the per-bound field earns before anything adopts it.

    An orphan `stops_*` is a consequence attached to no number. A non-answer in
    one is the field dropped in the spelling `bundle_gate.NON_ANSWERS` exists
    for. And a bundle carrying the field for SOME of its bounds is half-adopted,
    which is how a column comes to read as complete while most of it is still the
    row-level fallback — so the unit is the BUNDLE, and landing them one file at
    a time stays green.
    """
    for rel, _pid, doc in parsed:
        carried, missing = 0, []
        for index, row in rows(doc):
            found = set(bounds_of(row))
            for key in row:
                if not key.startswith(STOPS):
                    continue
                name = key[len(STOPS) :]
                if f"{BOUND}{name}" not in found:
                    findings.append(
                        f"{rel} method #{index}: `{key}` names no `{BOUND}{name}`"
                        " in its own row — a consequence attached to no number is"
                        " prose in a field the table reads as evidence"
                    )
                    continue
                if not bundle_gate.answers(row[key]):
                    findings.append(
                        f"{rel} method #{index}: `{key}` is {row[key]!r}, which"
                        " answers nothing — a bound whose consequence is a"
                        " non-answer is the column dropped in a spelling the"
                        " roster cannot see"
                    )
            for key in sorted(found):
                name = key[len(BOUND) :]
                if f"{STOPS}{name}" in row:
                    carried += 1
                else:
                    missing.append(f"#{index} `{key}`")
        if carried and missing:
            findings.append(
                f"{rel}: {carried} bound(s) carry a `{STOPS}*` consequence and"
                f" {len(missing)} do not ({', '.join(missing[:4])}"
                f"{' …' if len(missing) > 4 else ''}) — a half-adopted column"
                " reads as complete while most of it is still the row note"
            )


def no_parallel_table(root, findings):
    """The table may not be re-typed: not in the slice's section, not elsewhere.

    Two directions, because closing one is what the six driven mutations
    exploited. The slice page keeps the SECTION — it is where a reader looks —
    and must point here and carry no table row of its own; and the header this
    page owns may occur in no other tracked markdown, which is the half a rule
    naming one page cannot have.
    """
    path = root / SLICE
    if path.is_file():
        text = path.read_text(encoding="utf-8")
        if SECTION not in text:
            findings.append(
                f"{SLICE} has no `{SECTION}` section — the page a reader reaches"
                " for the bounds has stopped naming them at all"
            )
        else:
            body = text.split(SECTION, 1)[1].split("\n## ", 1)[0]
            typed = [line for line in body.splitlines() if line.startswith("|")]
            if typed:
                findings.append(
                    f"{SLICE} `{SECTION}` carries {len(typed)} table line(s) of"
                    f" its own — the bounds are {ARTIFACT}'s and a second table"
                    " beside them is what stage 4's exit calls written in parallel"
                )
            if ARTIFACT.name not in body:
                findings.append(
                    f"{SLICE} `{SECTION}` does not name {ARTIFACT.name} — the"
                    " section that lost its table owes the reader where the table"
                    " went"
                )
    for rel in claims_gate.markdown(root):
        if rel == str(ARTIFACT):
            continue
        if TABLE_HEADER in (root / rel).read_text(errors="replace"):
            findings.append(
                f"{rel} carries this page's table header — the bounds table is"
                f" generated into {ARTIFACT} and a second copy of it anywhere is"
                " a copy that rots"
            )


def check_floors(root, records, findings, bundle_floor, row_floor, bounds_floor, prose_floor):
    """Under the measurement, so a derivation that COLLAPSED is red.

    Scoped the way this tree scopes every such floor: to "the source is there and
    the derivation found none of it". A checkout with no bundle directory has no
    bounds, which is a fact; a directory of eight bundles resolving to no bound
    is a reader that stopped reading.
    """
    if not (root / BUNDLES).is_dir():
        return
    seen = {(r["bundle"], r["property"]) for r in records}
    method_rows = {(r["bundle"], r["index"]) for r in records}
    carried = [r for r in records if r["stops"] is not None]
    if len(seen) < bundle_floor:
        findings.append(
            f"{len(seen)} bundle(s) reached this table, under the floor of"
            f" {bundle_floor} — a closed slice whose bounds stopped being"
            " rendered is a slice whose scope table went back to being nobody's"
        )
    if len(method_rows) < row_floor:
        findings.append(
            f"{len(method_rows)} method row(s) carry a bound, under the floor of"
            f" {row_floor} — the attribution collapsed, and a bound with no row"
            " is a number with no obligation behind it"
        )
    if len(records) < bounds_floor:
        findings.append(
            f"{len(records)} `{BOUND}*` key(s) rendered, under the floor of"
            f" {bounds_floor} — the bundles carry them and this page is what"
            " shows them, so a smaller number is a filter and not a tree"
        )
    if len(carried) < prose_floor:
        findings.append(
            f"{len(carried)} bound(s) carry a `{STOPS}*` consequence, under the"
            f" floor of {prose_floor} — the column went backwards"
        )


def check_tranche(root, findings):
    """The ledger's own row set still resolves, or the page's denominator is 0.

    Floored the way every derivation here is floored — the SOURCE is there and
    this found none of it. Without it, renaming the tranche prints "0 of 0 rows
    carry no bundle", which reads as a complete tree and is a reader that
    stopped.
    """
    if (root / LEDGER).is_file() and not launch_tranche(root):
        findings.append(
            f"{LEDGER} resolves no `{LAUNCH}` row — the page's denominator then"
            " reads 0 and every bundle looks like the whole of it"
        )


def check_page(root, records, findings):
    """The page on disk shows every bound the bundles carry, and no others.

    Read off the FILE and not off the string `render` returned: a filter inside
    the renderer and a hand edit to the page are the same defect from a reader's
    side, and the byte diff below sees only the second.
    """
    path = root / ARTIFACT
    if not path.is_file():
        return
    printed = len(BOUND_ROW.findall(path.read_text(encoding="utf-8")))
    if printed != len(records):
        findings.append(
            f"{ARTIFACT} prints {printed} bound row(s) against the"
            f" {len(records)} the bundles carry — every `{BOUND}*` key of every"
            " bundle is this page's subject, and a table that drops one is the"
            " hand-written table again with a generator's header on it"
        )


def summary_rows(records):
    """(property, invariant, bundle, method rows, bounds, carried) per bundle."""
    out = []
    for pid in sorted({r["property"] for r in records}):
        mine = [r for r in records if r["property"] == pid]
        out.append(
            (
                pid,
                mine[0]["invariant"],
                mine[0]["bundle"],
                len({r["index"] for r in mine}),
                len(mine),
                len([r for r in mine if r["stops"] is not None]),
            )
        )
    return out


def cell(value):
    """A bound's value as one table cell, whatever TOML type it arrived as."""
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, (int, float)):
        return f"`{value}`"
    if isinstance(value, list):
        return ", ".join(f"`{item}`" for item in value)
    return str(value).replace("|", "\\|")


def prose(value):
    """A bundle string as one table cell: pipes escaped, newlines flattened."""
    return " ".join(str(value).split()).replace("|", "\\|")


def render(root, records=None):
    """`docs/assurance-bounds.md` as the tree makes it."""
    records = table(bundles(root, [])) if records is None else records
    carried = len([r for r in records if r["stops"] is not None])
    tranche, bundled = launch_tranche(root), sorted({r["property"] for r in records})
    unbundled = [pid for pid in tranche if pid not in bundled]
    missing = ", ".join(f"`{pid}`" for pid in unbundled) or "none"
    families = sorted({pid.rsplit("-", 1)[0] for pid in bundled})
    out = [
        "<!-- SPDX-License-Identifier: AGPL-3.0-only -->",
        "<!-- Copyright (C) 2026 RS-Key contributors -->",
        f"<!-- {GENERATED_BY} — do not edit by hand -->",
        "",
        "# Bounds",
        "",
        claims_gate.DISCLAIMER_PARAGRAPH,
        "",
        "Every bound every closed slice was taken at, and what each one stops"
        " being proved. The rows are not written here: they are read out of"
        " `assurance/bundle/*.toml`, one per `bound_*` key, by"
        " `scripts/bounds_gate.py`, which regenerates this page on every gate run"
        " and refuses a stale copy of it.",
        "",
        "It replaces a hand-typed table. Fourteen rows stood under `The bounds`"
        " in [the slice design](authorization-slice.md), no script read them, and"
        " six mutations — a docs bound moved while the bundle stood still, a"
        " bundle bound moved while the docs stood still, a row renamed after a"
        " constant that does not exist, a row deleted — were green on all eight"
        " gates. A number a reader trusts and no gate reads is the defect this"
        " page exists to end.",
        "",
        "## What is rendered",
        "",
        f"**Every bundle the tree has — {len(bundled)} of them.** Not the first"
        " slice's alone: the exit criterion says *the slice's bundle* because"
        " there was one when it was written, and rendering one now would leave"
        " most of the tree's bounds unshown, which is the same table written in"
        " parallel with a smaller denominator.",
        "",
        f"Every one of the {len(bundled)} is a `{LAUNCH}` row of"
        f" `assurance/configurations.toml`, all in the {' and '.join(families)}"
        " family, so *all the bundles* and *the P0-launch rows that have any raw"
        " evidence at all* are one set. The rest of that tranche is the"
        f" difference, derived here rather than typed: **{len(unbundled)} of its"
        f" {len(tranche)} rows** carry no bundle, so there is nothing to render"
        f" for them — {missing}.",
        "",
        "| Property | Invariant | Bundle | Method rows | Bounds | With a per-bound consequence |",
        "|---|---|---|---:|---:|---:|",
    ]
    for pid, invariant, bundle, method_rows, count, has in summary_rows(records):
        out.append(
            f"| `{pid}` | `{invariant}` | `{bundle}` | {method_rows} |"
            f" {count} | {has} |"
        )
    out += [
        "",
        f"**{carried} of {len(records)}** bounds carry a per-bound consequence."
        " The column is `stops_<name>` beside `bound_<name>` in the bundle — the"
        " same way `shipped_relation` already travels with a method row, one"
        " field down — so the consequence moves with the number instead of being"
        " re-typed beside it. A cell reading `—` would be a bound the bundle"
        " carries no such field for; what such a bound costs is then only in its"
        " row's `shipped_relation`, printed under each table as the row note.",
        "",
        "## The bounds, by property",
        "",
    ]
    for pid in sorted({r["property"] for r in records}):
        mine = [r for r in records if r["property"] == pid]
        out += [f"### `{pid}` — `{mine[0]['invariant']}`", ""]
        for index in sorted({r["index"] for r in mine}):
            row = [r for r in mine if r["index"] == index]
            first = row[0]
            out += [
                f"#### Method {index} — {prose(first['obligation'])}",
                "",
                f"`{first['method']}` over {prose(first['artifact'])}."
                f" cfg: {prose(first['cfg'])}. features: {prose(first['features'])}.",
                "",
                TABLE_HEADER,
                "|---|---|---|",
            ]
            for record in row:
                stops = (
                    prose(record["stops"]) if record["stops"] is not None else "—"
                )
                out.append(
                    f"| `{BOUND}{record['bound']}` | {cell(record['value'])} |"
                    f" {stops} |"
                )
            out += [
                "",
                f"> **Row note (`shipped_relation`).** {prose(first['relation'])}",
                "",
            ]
    return "\n".join(out)


def audit(
    root,
    bundle_floor: int = BUNDLE_FLOOR,
    row_floor: int = ROW_FLOOR,
    bounds_floor: int = BOUNDS_FLOOR,
    prose_floor: int = PROSE_FLOOR,
):
    """(findings, one-line summary) for the bounds, their column and their page."""
    root = pathlib.Path(root)
    findings = []
    parsed = bundles(root, findings)
    records = table(parsed)
    check_consequences(parsed, findings)
    check_tranche(root, findings)
    check_floors(
        root, records, findings, bundle_floor, row_floor, bounds_floor, prose_floor
    )
    no_parallel_table(root, findings)
    check_page(root, records, findings)

    try:
        want = render(root, records)
    except (OSError, ValueError, KeyError, TypeError) as error:
        findings.append(f"{ARTIFACT} cannot be generated: {error}")
    else:
        path = root / ARTIFACT
        got = path.read_text(encoding="utf-8") if path.is_file() else ""
        if got != want:
            findings.append(
                f"{ARTIFACT} is not what the generator writes — run"
                " `python scripts/bounds_gate.py --write` and commit the result"
            )

    carried = len([r for r in records if r["stops"] is not None])
    summary = (
        f"bounds-gate: ok — {len(records)} bounds over"
        f" {len({(r['bundle'], r['index']) for r in records})} method rows in"
        f" {len({r['property'] for r in records})} bundles, {carried} carrying a"
        " per-bound consequence"
    )
    return findings, summary


def run(root, write=False):
    if write:
        (root / ARTIFACT).write_text(render(root), encoding="utf-8")
        print(f"bounds-gate: wrote {ARTIFACT}")
        return 0
    findings, summary = audit(root)
    if findings:
        print("bounds-gate:", file=sys.stderr)
        for finding in findings:
            print(f"  {finding}", file=sys.stderr)
        return 1
    print(summary)
    return 0


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if argv and argv != ["--write"]:
        print("usage: bounds_gate.py [--write]", file=sys.stderr)
        return 2
    return run(ROOT, write=bool(argv))


if __name__ == "__main__":
    raise SystemExit(main())
