#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
"""Hold `formal/*.cfg` against the generator whose header they all carry.

233 of the 234 configurations start with "Generated by formal/gen-configs.sh --
do not edit by hand", and until this row nothing made that sentence true. Two
edits were silent, both measured:

* **Delete a generated configuration.** `assurance_gate.check_tiers` compares
  what `run-tlc.sh --tiers` lists against what `formal/` holds — but the tiers
  name whole families with `ls`, so `tiered` and `present` shrink *together*.
  Deleting all three `BootCarryMut_*.cfg` left every gate row green and the
  matrix three mutants shorter.
* **Edit a generated configuration by hand.** Flipping a constant in one of them
  changes what TLC checks and nothing compares the file to its source.

So: regenerate into a temp directory and diff. A missing file, a hand-edited
file, and a generator changed without regenerating are the same finding here,
which is right — all three mean the committed matrix is not the one the
generator describes.

What this does **not** catch, deliberately: deleting a family from
`gen-configs.sh` *and* from `formal/` in one commit. That is a visible diff in
the file whose whole content is the roster, which is where it belongs; a guard
cannot tell a deletion from a decision.
"""

import fnmatch
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]

GENERATOR = "formal/gen-configs.sh"
CONFIG_DIR = "formal"

#: The configurations `gen-configs.sh` does not write, each with the reason a
#: reader needs. Checked in both directions: an entry whose file has gone is a
#: stale carve-out, and one the generator has started writing is a contradiction.
HAND_WRITTEN = {
    "TokenExport.cfg": "serialization-only TLC input consumed by "
    "scripts/export_token_relation.py — it has no mutation family and no tier row",
}

#: What every generated configuration says about itself. A hand-written one must
#: not claim it: the header is what tells a reader not to edit the file, and a
#: file that carries it while nothing regenerates it is the lie this row is for.
HEADER = "Generated by formal/gen-configs.sh"

#: The generator's own list of the PAIRS that may legitimately be byte-for-byte
#: twins, READ rather than copied. There is exactly one today — TLC takes the
#: module as an argument, so `TraceSeamsBad.cfg` and `TraceSeams.cfg` are two
#: experiments over two modules with one configuration between them. A second
#: copy of that list here is the defect this row's whole family exists to catch,
#: one file over; a spelling change in `gen-configs.sh` costs a finding rather
#: than a silent exemption.
#:
#: A PAIR and not a name, and that correction was the sixth hole of the family:
#: the first edition exempted `TraceSeamsBad.cfg` from being ANYBODY's twin, so
#: `cp Shipped.cfg TraceSeamsBad.cfg` passed both guards while the pair the
#: exemption was granted for had gone.
DUP_CARVE_OUT = re.compile(r'^DUP_OK="([^"]*)"', re.M)

#: The runner's `spec_for`, whose arms are what make an identical pair two
#: experiments. Read out of the runner rather than restated, for the reason
#: `verdict_gate.RUNNER_READS` gives: the two disagreeing is the defect.
RUNNER = "formal/run-tlc.sh"
SPEC_FOR = re.compile(r"^spec_for\(\)\s*\{(.*)$", re.M)
SPEC_ARM = re.compile(r"([^\s;()|]+)\)\s*echo\s+(\S+)\s*;;")

#: Below this the generator did not run. A generator invoked with an output
#: directory it ignores writes nothing there, every comparison loops over an
#: empty set, and the row reads as a pass — the shape five guards in this tree
#: have shipped with. Well under the 200 it writes today, and far above 0.
FLOOR = 100


def generate(root: pathlib.Path, into: pathlib.Path) -> tuple[int, str]:
    """(exit code, stderr) for a regeneration into `into`."""
    done = subprocess.run(
        [str(root / GENERATOR), str(into)],
        capture_output=True,
        text=True,
    )
    return done.returncode, done.stderr


def first_difference(want: bytes, got: bytes) -> str:
    """The first line where two configurations part, as a reader would say it.

    Bytes, not text: `read_text` folds `\r\n` to `\n`, so a CRLF copy compared
    as text is equal to a LF one — and the row's own summary says byte-for-byte.
    `split`, not `splitlines`: a trailing newline then shows up as a part of its
    own, so the length branch always has something true to say — where
    `splitlines` made "54 lines and 54 lines" the explanation for a difference,
    and broke on the separators `\x0b`, `\x0c` and `\x85` besides.
    """
    a, b = want.split(b"\n"), got.split(b"\n")
    for n, (x, y) in enumerate(zip(a, b), 1):
        if x != y:
            return f"line {n}: generator writes {x!r}, the tree has {y!r}"
    return (
        f"every line they share is equal; the generator writes {len(a)}"
        f" newline-separated part(s) and the tree has {len(b)} — a truncation, or"
        " a trailing newline that moved"
    )


def identical_pairs(bodies):
    """(later, first) for every configuration whose bytes another already has.

    Sorted, so the pair reads the same way the generator's own `*.cfg` sweep
    reports it — the two naming a different member of the pair would be two
    findings for one file, and the reader would go looking for a second defect.
    """
    seen: dict[bytes, str] = {}
    pairs = []
    for name in sorted(bodies):
        owner = seen.setdefault(bodies[name], name)
        if owner != name:
            pairs.append((name, owner))
    return pairs


def check_duplicates(root, bodies, problems):
    """No two configurations may be one file, and the carve-out is checked back.

    THE MEASURED HOLE. `Historical_E76.cfg` and `Mut_BugSeedDoesNotLead.cfg`
    were byte-identical from 301c53a, the commit that introduced them, to the one
    that added this: `gen-configs.sh` emitted both with the same four arguments,
    so two rows of the weekly matrix ran ONE experiment, both were paid for in
    wall clock, and every counter derived by grepping `formal/*.cfg` counted the
    same configuration twice — `SEC-FIDO-005`'s `cfgs = 40` was 39. Nothing
    compared two configurations with each other; every check above compares a
    configuration with its generator, which two identical files both pass.

    Held on the TREE and not on the generator's output, because those are two
    different findings: the generator refuses to write a duplicate itself, and
    what only this side can see is a duplicate involving a HAND-WRITTEN
    configuration, which no emitter writes and no regeneration would remove.
    """
    text = (root / GENERATOR).read_text(encoding="utf-8")
    carve = DUP_CARVE_OUT.search(text)
    if carve is None:
        problems.append(
            f"{GENERATOR}: no `DUP_OK=\"…\"` line — the generator's own list of pairs"
            " that may legitimately be twins cannot be read, and reading it as EMPTY"
            " would report the trace pair as a defect")
        return
    allowed = {tuple(entry.split(":", 1)) for entry in carve.group(1).split()
               if ":" in entry}
    pairs = identical_pairs(bodies)
    for pair in pairs:
        if pair in allowed:
            continue
        problems.append(
            f"{pair[0]}: byte-identical to {pair[1]} — two names, one configuration, so"
            " the matrix runs one experiment twice and every count derived from"
            f" {CONFIG_DIR}/*.cfg counts it twice")
    for pair in sorted(allowed - set(pairs)):
        problems.append(
            f"{pair[0]}:{pair[1]}: named in {GENERATOR}'s DUP_OK as a legitimately"
            " identical pair, but they are not each other's twin now — a stale carve-out"
            " reads like a rule")
    check_carve_out_premise(root, allowed & set(pairs), problems)


def module_map(root):
    """`spec_for`'s arms as (glob, module), in the order a shell `case` takes them."""
    found = SPEC_FOR.search((root / RUNNER).read_text(encoding="utf-8"))
    return SPEC_ARM.findall(found.group(1)) if found else []


def module_of(arms, name):
    """The module `run-tlc.sh` would hand TLC for `name`, or None."""
    for glob, module in arms:
        if fnmatch.fnmatchcase(name, glob):
            return module
    return None


def check_carve_out_premise(root, granted, problems):
    """An exempt pair must actually be two experiments, and this is what asks.

    The generator asserts the pair; the reason it is legitimate is that TLC takes
    the MODULE as an argument and `spec_for` routes the two names apart. That
    routing is keyed on the FILENAME, so a rename — or an arm moved above another
    in the `case` — silently makes the pair one experiment again, and the
    exemption would still be granted. The generator cannot ask (the runner is not
    beside it in every tree it generates into); this side can.
    """
    arms = module_map(root)
    if not arms:
        problems.append(
            f"{RUNNER}: `spec_for` no longer reads as a `case` of `<glob>) echo <module>"
            " ;;` arms — the premise of every DUP_OK pair is then checked by nothing")
        return
    for later, owner in sorted(granted):
        mine, theirs = module_of(arms, later), module_of(arms, owner)
        if mine is not None and theirs is not None and mine != theirs:
            continue
        problems.append(
            f"{later}:{owner}: exempt as a legitimately identical pair, but {RUNNER}"
            f" sends both to {mine} — identical bytes AND one module is one experiment"
            " under two names, which is the thing the exemption is not for")


def summary_line(generated: int) -> str:
    """Counted from what the GENERATOR wrote, never from what the tree holds: a
    summary derived from `present` cannot notice the generator gaining a file."""
    return (
        f"config-gen-gate: ok — {generated} generated configuration(s) reproduce"
        f" byte-for-byte, {len(HAND_WRITTEN)} hand-written"
    )


def audit(root):
    """(problems, one-line summary) for how `formal/*.cfg` matches its generator."""
    root = pathlib.Path(root)
    problems: list[str] = []
    bodies = {}
    for path in (root / CONFIG_DIR).glob("*.cfg"):
        if path.is_file():
            bodies[path.name] = path.read_bytes()
        else:
            problems.append(f"{path.name}: a {CONFIG_DIR}/*.cfg entry that is not a regular file")
    present = set(bodies)

    with tempfile.TemporaryDirectory() as tmp:
        into = pathlib.Path(tmp)
        code, stderr = generate(root, into)
        if code != 0:
            tail = stderr.strip().splitlines()[-1:] or ["no stderr"]
            # ONE cause, ONE message. Everything below would also fire — a dead
            # generator wrote nothing, so all 200 files read as unregistered —
            # and 202 findings for one broken line is the report defect where a
            # reader is told the tree is wrong when the generator is.
            problems.append(f"{GENERATOR} exited {code}: {tail[0]}")
            return problems, summary_line(0)
        written = {p.name: p.read_bytes() for p in into.glob("*.cfg")}

        if len(written) < FLOOR:
            problems.append(
                f"{GENERATOR} wrote {len(written)} configurations, under the floor of"
                f" {FLOOR} — it did not run, or it ignored its output directory"
            )
        for name in sorted(set(written) - present):
            problems.append(
                f"{name}: {GENERATOR} writes it and {CONFIG_DIR}/ does not have it"
                " — regenerate, or the matrix row it belongs to runs nothing"
            )
        for name in sorted(present - set(written) - set(HAND_WRITTEN)):
            problems.append(
                f"{name}: neither generated nor registered hand-written in"
                " scripts/config_gen_gate.py — say which it is"
            )
        for name in sorted(set(written) & present):
            got = bodies[name]
            if got != written[name]:
                problems.append(
                    f"{name}: differs from what {GENERATOR} writes —"
                    f" {first_difference(written[name], got)}"
                )
        # The sentence this row is named after, held on the side that has 200
        # files. Without it the generator could stop writing the header, the
        # tree could be regenerated to agree, and every `.cfg` would tell its
        # next reader nothing while the row said ok.
        for name in sorted(written):
            if not written[name].startswith(b"\\* " + HEADER.encode()):
                problems.append(
                    f"{name}: {GENERATOR} writes it without the {HEADER!r} header —"
                    " the one line that tells a reader not to edit it by hand"
                )
        for name in sorted(set(HAND_WRITTEN) & set(written)):
            problems.append(
                f"{name}: registered hand-written but {GENERATOR} writes it —"
                " drop the carve-out, or stop generating it"
            )
        generated = len(written)

    check_duplicates(root, bodies, problems)

    for name in sorted(set(HAND_WRITTEN) - present):
        problems.append(f"{name}: registered hand-written but no such file — stale entry")
    for name in sorted(set(HAND_WRITTEN) & present):
        if HEADER in (root / CONFIG_DIR / name).read_text():
            problems.append(
                f"{name}: registered hand-written but carries the {HEADER!r} header,"
                " which tells its next reader not to edit the one file they may"
            )

    return problems, summary_line(generated)


def run(root: pathlib.Path) -> int:
    problems, summary = audit(root)
    if problems:
        print(f"config-gen-gate: {len(problems)} finding(s)", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print("  run `./formal/gen-configs.sh` and commit the result", file=sys.stderr)
        return 1
    print(summary)
    return 0


def main():
    if sys.argv[1:]:
        print("usage: config_gen_gate.py", file=sys.stderr)
        return 2
    return run(ROOT)


if __name__ == "__main__":
    sys.exit(main())
