#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
"""Hold `formal/*.cfg` against the generator whose header they all carry.

187 of the 188 configurations start with "Generated by formal/gen-configs.sh --
do not edit by hand", and until this row nothing made that sentence true. Two
edits were silent, both measured:

* **Delete a generated configuration.** `assurance_gate.check_tiers` compares
  what `run-tlc.sh --tiers` lists against what `formal/` holds — but the tiers
  name whole families with `ls`, so `tiered` and `present` shrink *together*.
  Deleting all three `BootCarryMut_*.cfg` left every gate row green and the
  matrix three mutants shorter.
* **Edit a generated configuration by hand.** Flipping a constant in one of them
  changes what TLC checks and nothing compares the file to its source.

So: regenerate into a temp directory and diff. A missing file, a hand-edited
file, and a generator changed without regenerating are the same finding here,
which is right — all three mean the committed matrix is not the one the
generator describes.

What this does **not** catch, deliberately: deleting a family from
`gen-configs.sh` *and* from `formal/` in one commit. That is a visible diff in
the file whose whole content is the roster, which is where it belongs; a guard
cannot tell a deletion from a decision.
"""

import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]

GENERATOR = "formal/gen-configs.sh"
CONFIG_DIR = "formal"

#: The configurations `gen-configs.sh` does not write, each with the reason a
#: reader needs. Checked in both directions: an entry whose file has gone is a
#: stale carve-out, and one the generator has started writing is a contradiction.
HAND_WRITTEN = {
    "TokenExport.cfg": "serialization-only TLC input consumed by "
    "scripts/export_token_relation.py — it has no mutation family and no tier row",
}

#: What every generated configuration says about itself. A hand-written one must
#: not claim it: the header is what tells a reader not to edit the file, and a
#: file that carries it while nothing regenerates it is the lie this row is for.
HEADER = "Generated by formal/gen-configs.sh"

#: Below this the generator did not run. A generator invoked with an output
#: directory it ignores writes nothing there, every comparison loops over an
#: empty set, and the row reads as a pass — the shape five guards in this tree
#: have shipped with. Well under the 187 it writes today, and far above 0.
FLOOR = 100


def generate(root: pathlib.Path, into: pathlib.Path) -> tuple[int, str]:
    """(exit code, stderr) for a regeneration into `into`."""
    done = subprocess.run(
        [str(root / GENERATOR), str(into)],
        capture_output=True,
        text=True,
    )
    return done.returncode, done.stderr


def first_difference(want: str, got: str) -> str:
    """The first line where two configurations part, as a reader would say it."""
    a, b = want.splitlines(), got.splitlines()
    for n, (x, y) in enumerate(zip(a, b), 1):
        if x != y:
            return f"line {n}: generator writes {x!r}, the tree has {y!r}"
    return f"the tree's copy is {len(b)} lines, the generator writes {len(a)}"


def audit(root):
    """(problems, one-line summary) for how `formal/*.cfg` matches its generator."""
    root = pathlib.Path(root)
    problems: list[str] = []
    present = {p.name for p in (root / CONFIG_DIR).glob("*.cfg")}

    with tempfile.TemporaryDirectory() as tmp:
        into = pathlib.Path(tmp)
        code, stderr = generate(root, into)
        if code != 0:
            tail = stderr.strip().splitlines()[-1:] or ["no stderr"]
            problems.append(f"{GENERATOR} exited {code}: {tail[0]}")
        written = {p.name: p.read_text() for p in into.glob("*.cfg")}

        if len(written) < FLOOR:
            problems.append(
                f"{GENERATOR} wrote {len(written)} configurations, under the floor of"
                f" {FLOOR} — it did not run, or it ignored its output directory"
            )
        for name in sorted(set(written) - present):
            problems.append(
                f"{name}: {GENERATOR} writes it and {CONFIG_DIR}/ does not have it"
                " — regenerate, or the matrix row it belongs to runs nothing"
            )
        for name in sorted(present - set(written) - set(HAND_WRITTEN)):
            problems.append(
                f"{name}: neither generated nor registered hand-written in"
                " scripts/config_gen_gate.py — say which it is"
            )
        for name in sorted(set(written) & present):
            got = (root / CONFIG_DIR / name).read_text()
            if got != written[name]:
                problems.append(
                    f"{name}: differs from what {GENERATOR} writes —"
                    f" {first_difference(written[name], got)}"
                )

    for name in sorted(set(HAND_WRITTEN) - present):
        problems.append(f"{name}: registered hand-written but no such file — stale entry")
    for name in sorted(set(HAND_WRITTEN) & present):
        if HEADER in (root / CONFIG_DIR / name).read_text():
            problems.append(
                f"{name}: registered hand-written but carries the {HEADER!r} header,"
                " which tells its next reader not to edit the one file they may"
            )

    summary = (
        f"config-gen-gate: ok — {len(present) - len(HAND_WRITTEN)} generated"
        f" configuration(s) reproduce byte-for-byte, {len(HAND_WRITTEN)} hand-written"
    )
    return problems, summary


def run(root: pathlib.Path) -> int:
    problems, summary = audit(root)
    if problems:
        print(f"config-gen-gate: {len(problems)} finding(s)", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print("  run `./formal/gen-configs.sh` and commit the result", file=sys.stderr)
        return 1
    print(summary)
    return 0


def main():
    if sys.argv[1:]:
        print("usage: config_gen_gate.py", file=sys.stderr)
        return 2
    return run(ROOT)


if __name__ == "__main__":
    sys.exit(main())
