# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
"""The mutation table `transport_bridge_gate.py` is verified against.

Same discipline as its siblings: for every rule, one mutation that must make the
row RED, and a CONTROL that must leave it GREEN — plus the family this tree keeps
shipping guards with, a regex that has stopped matching and therefore finds
nothing, loops over nothing and exits 0. Each case asserts its patch anchor
resolved, so a fixture that has drifted fails loudly instead of mutating nothing.

The floor is a PARAMETER of the fixture, not a global a case reaches in and
lowers: `Tree.write_scopes(n)` is how a case moves it, and the audit reads it
back out of the file like the real one does.
"""

import pathlib

import pytest

import transport_bridge_gate as gate

pytestmark = pytest.mark.assurance

BRIDGE = """\
// SPDX-License-Identifier: AGPL-3.0-only
#[cfg(kani)]
pub const PROBE_CHUNKS: usize = 2;
#[cfg(not(kani))]
pub const PROBE_CHUNKS: usize = 128;

/// `formal/Transport.cfg` runs `Cap = 3` and `formal/scopes.txt` records 2.
pub const PROBE_MAX: usize = CTAP_MAX_MESSAGE;
"""

REASSEMBLER = """\
// SPDX-License-Identifier: AGPL-3.0-only
#[cfg(not(kani))]
pub const CTAP_MAX_MESSAGE: usize = INIT_DATA + 128 * CONT_DATA; // 7609
#[cfg(kani)]
pub const CTAP_MAX_MESSAGE: usize = INIT_DATA + 2 * CONT_DATA;
"""

CONFIG = """\
\\* Generated by formal/gen-configs.sh -- do not edit by hand.
SPECIFICATION Spec
CONSTANTS
    Channels = {"a", "b"}
    Cap = 3
INVARIANTS
    TypeOK
"""

SCOPES = """\
\\* the fixture's scope record
RSKeyTransport         Channels               2   NoCrossChannelSplice
RSKeyTransport         Cap                    {floor}   NoBufferOverrun
"""


class Tree:
    def __init__(self, root):
        self.root = root
        self.write(gate.BRIDGE, BRIDGE)
        self.write(gate.REASSEMBLER, REASSEMBLER)
        self.write(gate.CONFIG, CONFIG)
        self.write_scopes(2)

    def write(self, rel, text):
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    def write_scopes(self, floor):
        """The recorded floor, as a parameter of the fixture rather than a global."""
        self.write(gate.SCOPES, SCOPES.format(floor=floor))

    def edit(self, rel, old, new):
        """Replace `old` once, failing loudly if the fixture no longer says it."""
        path = self.root / rel
        text = path.read_text()
        assert text.count(old) == 1, f"{rel} does not say {old!r} exactly once"
        path.write_text(text.replace(old, new))

    def problems(self):
        return gate.audit(self.root)[0]


@pytest.fixture
def tree(tmp_path):
    return Tree(tmp_path)


def only(problems, needle):
    return [p for p in problems if needle in p]


# --- the controls -------------------------------------------------------------


def test_the_fixture_is_green(tree):
    """CONTROL. A table whose green case is not green measures nothing below."""
    assert tree.problems() == []


def test_the_real_tree_is_green():
    """The other control, and the one that cannot be a fixture."""
    assert gate.audit(gate.ROOT)[0] == []


def test_an_unrelated_edit_leaves_it_green(tree):
    """The false-alarm control: a guard that fires on ordinary work gets deleted."""
    tree.edit(gate.REASSEMBLER, "// 7609", "// 7609 bytes, one INIT and 128 CONTs")
    assert tree.problems() == []


# --- rule 1: the posed width IS the recorded floor -----------------------------


def test_a_shrink_that_leaves_the_floor_behind_is_caught(tree):
    tree.edit(gate.BRIDGE, "#[cfg(kani)]\npub const PROBE_CHUNKS: usize = 2;",
              "#[cfg(kani)]\npub const PROBE_CHUNKS: usize = 3;")
    assert only(tree.problems(), "do not pose the bound they say they pose")


def test_a_floor_that_moves_under_the_harness_is_caught(tree):
    tree.write_scopes(3)
    assert only(tree.problems(), "do not pose the bound they say they pose")


# --- rule 2: the configuration is at or above the floor ------------------------


def test_a_configuration_below_the_floor_is_caught(tree):
    tree.edit(gate.CONFIG, "Cap = 3", "Cap = 1")
    assert only(tree.problems(), "is under")


# --- rule 3: the prose names the configuration's real Cap ----------------------


def test_the_configuration_moving_without_the_prose_is_caught(tree):
    """The constructed defect this gate exists for: `Cap = 3 -> 4` moved the
    configuration and left every other gate green, because the floor is a `>=`
    and no Rust file mentions it."""
    tree.edit(gate.CONFIG, "Cap = 3", "Cap = 4")
    assert only(tree.problems(), "the sentence is the only place these two")


def test_the_prose_moving_without_the_configuration_is_caught(tree):
    """The same rule from the other side — a page cannot re-point itself."""
    tree.edit(gate.BRIDGE, "runs `Cap = 3`", "runs `Cap = 9`")
    assert only(tree.problems(), "the sentence is the only place these two")


# --- rule 4: the shipped arm IS the shipped multiplier -------------------------


def test_a_shipped_width_that_moves_alone_is_caught(tree):
    tree.edit(gate.REASSEMBLER, "INIT_DATA + 128 * CONT_DATA", "INIT_DATA + 64 * CONT_DATA")
    assert only(tree.problems(), "builds CTAP_MAX_MESSAGE from 64 continuations")


def test_the_shipped_arm_is_not_read_off_the_kani_one(tree):
    """The defect the first run of this guard had: an unanchored pattern matched
    BOTH `CTAP_MAX_MESSAGE` definitions and would have read 2 as the shipped
    width. Deleting the shipped arm must be a problem, not a silent fallback."""
    tree.edit(
        gate.REASSEMBLER,
        "#[cfg(not(kani))]\npub const CTAP_MAX_MESSAGE: usize = INIT_DATA + 128 * CONT_DATA; // 7609\n",
        "",
    )
    assert only(tree.problems(), "matched 0 time(s)")


# --- the family every guard in this tree has shipped with ----------------------


@pytest.mark.parametrize(
    "rel, old, needle",
    [
        (gate.CONFIG, "    Cap = 3\n", "Cap matched 0 time(s)"),
        (gate.SCOPES, "RSKeyTransport         Cap                    2   NoBufferOverrun\n",
         "floor matched 0 time(s)"),
        (gate.BRIDGE, "/// `formal/Transport.cfg` runs `Cap = 3` and `formal/scopes.txt` records 2.\n",
         "sentence matched 0 time(s)"),
    ],
)
def test_a_pattern_that_stops_matching_is_a_problem_not_a_pass(tree, rel, old, needle):
    """A regex that finds nothing loops over nothing and exits 0 — five guards in
    this tree shipped with exactly that hole, so every read goes through `one`."""
    tree.edit(rel, old, "")
    assert only(tree.problems(), needle), tree.problems()


def test_a_missing_arm_is_named_rather_than_defaulted(tree):
    tree.edit(gate.BRIDGE, "#[cfg(kani)]\npub const PROBE_CHUNKS: usize = 2;\n", "")
    assert only(tree.problems(), "needs a kani arm and a not(kani) arm")


@pytest.mark.parametrize("rel", [gate.BRIDGE, gate.REASSEMBLER, gate.CONFIG, gate.SCOPES])
def test_a_deleted_input_is_a_problem(tree, rel):
    """Reading a file that is gone must fail, not skip: the shape where a guard
    silently stops covering the thing it was written for."""
    (tree.root / rel).unlink()
    assert only(tree.problems(), "is gone; the transport bridge is unchecked")


def test_every_rule_has_a_case():
    """The roster half: a rule added without a case is the hole this file exists
    for, and the count is asserted rather than trusted to review."""
    cases = [n for n in globals() if n.startswith("test_")]
    assert len(cases) >= 12, cases
    assert pathlib.Path(gate.__file__).is_file()
