# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
"""The mutation table `evidence_gate.py` is verified against.

Every rule is broken once on a fixture and the break must be the finding it
claims to be, then the real checkout closes the other direction: a guard that
cannot go green is deleted as fast as one that cannot go red.

Two cases are here because the derivation was measured WRONG before it shipped,
and both are the same family — a rule closed in one spelling of the thing it is
about. `trace_data_modules` first asked whether `check.sh` names the generator
and, anywhere in the same file, a recorded session; `RSKeySecurityState` names
`ghost_gate.py`, `ghost_gate.py` has a row, and a different row names the
session — so 92 configurations came back trace-linked instead of 11 and every
FIDO property grew trace evidence it does not have. And a bundle listing
hardware among its ABSENT subjects is the honest case the tree actually has, so
a rule that matched the key by prefix would have reddened the only bundle here
for saying it has no board result.
"""

import pathlib
import re
import subprocess
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import assurance_gate
import evidence_gate
import gate_lines
import platform_gate
# The GFM split model and the poison, imported rather than retyped: what splits a
# markdown row is one fact about one renderer, and the escape both pages use is
# one function. A second copy is a second answer that agrees until one is redone.
import test_platform_gate as P

ROOT = pathlib.Path(__file__).resolve().parents[1]

MINI = """\
---- MODULE Mini ----
CONSTANTS
    Fids

TypeOK == TRUE
FooStaysClosed == foo = FALSE
BarNeverOpens == bar = FALSE
Init == foo = FALSE
Next == UNCHANGED foo
Spec == Init /\\ [][Next]_foo
====
"""

#: The generated half of the replay harness: it names the script that writes it,
#: which is one half of the handshake `trace_data_modules` asks for.
REPLAY_DATA = """\
---- MODULE ReplayData ----
(* Generated by scripts/replay_gen.py from a recorded session. *)
EXTENDS Mini

Events == <<>>
====
"""

REPLAY = """\
---- MODULE Replay ----
EXTENDS ReplayData

TraceInit == TRUE
TraceNext == TRUE
TraceSpec == TraceInit /\\ [][TraceNext]_foo
====
"""

SHIPPED_CFG = """\
SPECIFICATION Spec
CONSTANTS
    Fids = {"f1"}
INVARIANTS
    TypeOK
    FooStaysClosed
    BarNeverOpens
"""

SOLO_CFG = """\
SPECIFICATION Spec
CONSTANTS
    Fids = {"f1"}
INVARIANTS
    TypeOK
    FooStaysClosed
"""

REPLAY_CFG = """\
SPECIFICATION TraceSpec
CONSTANTS
    Fids = {"f1"}
INVARIANTS
    TypeOK
    BarNeverOpens
"""

#: The verdict registry, so a configuration that NAMES an invariant can be told
#: from one that ASSERTS it. `ReplayBad.cfg` is the negative session: it replays
#: and must be refused, which is evidence of a different kind from acceptance.
FLOORS = """\
Shipped.cfg     GREEN   1
Replay.cfg      GREEN   1
ReplayBad.cfg   RED     -       -       BarNeverOpens
Solo_*.cfg      RED     -
"""

#: The observed-run record, present because `run_count_gate` makes it mandatory —
#: a tree without it has recorded no run at all — and because the freshness axis
#: now dates a modelled property against it. The axis reads this file's PATH and
#: not its content, so one row is enough; what it has to be is a file the fixture
#: can commit and then move.
RUNS = """\
[[run]]
tier = "safety"
command = "./formal/run-tlc.sh safety"
date = "2026-01-01"
commit = "0000000000000000000000000000000000000000"
host = "a fixture"
workers = 2
matrix = '''
Shipped.cfg    GREEN   states=1  distinct=1  depth=1  1s
'''
"""

COMUTANTS = """\
pending_floor = 0

[comutant.BugFooOpens]
status = "patch"
expect = "killed"
file = "crates/rsk-a/src/twin.rs"
find = "closed"
replace = "open"
"""

CHECK_SH = """\
#!/usr/bin/env bash
run() { echo "== $1 =="; shift; "$@"; }
run "replay data" python scripts/replay_gen.py formal/traces/session.jsonl
run "something else" python scripts/other_gate.py
"""

PROPERTIES = """\
[[property]]
id = "SEC-T-001"
name = "FooStaysClosed"
status = "BOUNDED"
statement = "Foo stays closed."
source = ["spec"]

[[property]]
id = "SEC-T-002"
name = "BarNeverOpens"
status = "MODELLED-ONLY"
statement = "Bar never opens."
source = ["spec"]

[[property]]
id = "SEC-R-001"
name = "RuledAwayRisk"
status = "ACCEPTED-RISK"
statement = "A ruled-away risk."
source = ["spec"]
ruling = "the maintainer said so, dated"
"""

#: The second assumption registry, as the hardware axis reads it: one
#: silicon-class obligation on the property, `pending`, which is the state the
#: real tree is in — a board result lands HERE, so an axis that did not read it
#: would print "no property was measured on a board" over one.
PLATFORM = """\
[[assumption]]
id = "PLAT-FLASH-001"
class = "flash"
statement = "The tear model is the one the store assumes."
discharge = "A recorded PASS on a throwaway board."
discharge_owner = "maintainer"
status = "pending"
failure_direction = "security: a torn write could leave a credential live"
supports = ["SEC-T-001"]
"""

CONFIGURATIONS = """\
[[cell]]
properties = ["SEC-T-001", "SEC-T-002"]
columns = ["firmware"]
disposition = "covered"

[[cell]]
properties = ["SEC-T-001"]
columns = ["firmware-pico"]
disposition = "equivalent"

[[cell]]
properties = ["SEC-T-002"]
columns = ["firmware-no-touch"]
disposition = "out-of-scope"
"""

LIB_RS = """\
// Refines `Mini!FooStaysClosed` — SEC-T-001.
pub fn keep_foo_closed() -> bool {
    true
}
"""

KANI_RS = """\
use super::*;

#[cfg_attr(kani, kani::proof)]
fn foo_stays_closed_probe() {}
"""


class Tree:
    """A checkout shaped like this one, small enough to break one rule at a time."""

    def __init__(self, root):
        self.root = pathlib.Path(root)
        self.write("formal/Mini.tla", MINI)
        self.write("formal/ReplayData.tla", REPLAY_DATA)
        self.write("formal/Replay.tla", REPLAY)
        self.write("formal/Shipped.cfg", SHIPPED_CFG)
        self.write("formal/Solo_BugFooOpens.cfg", SOLO_CFG)
        self.write("formal/Replay.cfg", REPLAY_CFG)
        self.write("formal/ReplayBad.cfg", REPLAY_CFG)
        self.write("formal/floors.txt", FLOORS)
        self.write("formal/runs.toml", RUNS)
        self.write("formal/comutants.toml", COMUTANTS)
        self.write("formal/traces/session.jsonl", '{"action": "Start"}\n')
        self.write("scripts/check.sh", CHECK_SH)
        self.write("scripts/replay_gen.py", "# writes formal/ReplayData.tla\n")
        self.write("scripts/other_gate.py", "# a guard with no session\n")
        self.write("crates/rsk-a/src/lib.rs", LIB_RS)
        self.write("crates/rsk-a/src/kani.rs", KANI_RS)
        # The co-refutation patch target: an owner with no `Refines` tag, which
        # is five of the seven the real bundle names.
        self.write("crates/rsk-a/src/twin.rs", "pub const DOOR: &str = \"closed\";\n")
        self.write("assurance/properties.toml", PROPERTIES)
        self.write("assurance/configurations.toml", CONFIGURATIONS)
        self.write("assurance/platform.toml", PLATFORM)
        self.git("init", "-q")
        self.commit("the tree the evidence is about")
        self.write("assurance/bundle/SEC-T-001.toml", self.bundle())
        self.regenerate()

    # --- the fixture's own mechanics -----------------------------------------

    def write(self, rel, text):
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    def edit(self, rel, old, new):
        """Replace `old` once, failing loudly if the fixture no longer says it."""
        path = self.root / rel
        text = path.read_text()
        assert text.count(old) == 1, f"{rel} does not say {old!r} exactly once"
        path.write_text(text.replace(old, new))

    def append(self, rel, text):
        (self.root / rel).write_text((self.root / rel).read_text() + text)

    def git(self, *args):
        subprocess.run(["git", "-C", str(self.root), *args], check=True, capture_output=True)

    def commit(self, subject):
        self.git("add", "-A")
        self.git(
            "-c", "user.name=t", "-c", "user.email=t@example.invalid",
            "commit", "-q", "-m", subject,
        )

    def head(self):
        done = subprocess.run(
            ["git", "-C", str(self.root), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        )
        return done.stdout.strip()

    def bundle(self, commit=None, extra_build="", subjects='["abstract model"]',
               method="model-check"):
        return (
            "[property]\n"
            'id = "SEC-T-001"\n'
            f"subjects = {subjects}\n"
            'subjects_absent = ["hardware", "binary"]\n'
            "\n[build]\n"
            f'commit = "{commit or self.head()}"\n'
            f"{extra_build}"
            "\n[[method]]\n"
            'obligation = "the invariant over the shipped constants"\n'
            f'method = "{method}"\n'
        )

    def regenerate(self):
        assurance_gate.co_refuted.cache_clear()
        self.write("docs/assurance-vector.md", evidence_gate.render(self.root))

    def problems(self):
        assurance_gate.co_refuted.cache_clear()
        return evidence_gate.audit(self.root)[0]

    def vector(self, pid):
        assurance_gate.co_refuted.cache_clear()
        for row in evidence_gate.vectors(self.root, []):
            if row["entry"]["id"] == pid:
                return row["vector"]
        raise AssertionError(f"{pid} is not in the fixture registry")


@pytest.fixture
def tree(tmp_path):
    return Tree(tmp_path)


def only(problems, needle):
    """The problems mentioning `needle`, so a message is asserted, not a count.

    On a failure this prints `assert []`, and the UNFILTERED list is on the
    `+ where … = problems()` line under it. Read that line: a neutered rule was
    reported as "the gate stayed silent" over seven cases where a NEIGHBOUR's
    rule had fired and `problems()` was never empty.
    """
    return [p for p in problems if needle in p]


# --- both directions of green -------------------------------------------------


def test_the_fixture_is_green(tree):
    assert tree.problems() == []


def test_this_checkout_is_green():
    findings, summary = evidence_gate.audit(ROOT)
    assert findings == [], findings
    assert summary.startswith("evidence-gate: ok")


def test_the_fixture_axes_are_the_ones_it_was_built_for(tree):
    """A fixture whose axes are all zero would pass every rule below vacuously."""
    foo, bar = tree.vector("SEC-T-001"), tree.vector("SEC-T-002")
    assert (foo["model"], foo["asserted"], foo["kani"], foo["co"]) == (2, 1, 1, 1)
    assert (bar["model"], bar["asserted"]) == (3, 2)
    assert (bar["trace"], bar["accepted"], bar["kani"]) == (2, 1, 0)
    assert foo["freshness"] == "fresh"


# --- the round trip: the v1 scalar rebuilds from two axes ---------------------


def test_every_status_in_the_real_registry_rebuilds():
    """Stage 1B's exit, over the live registry rather than over a fixture."""
    rows = evidence_gate.vectors(ROOT, [])
    assert len(rows) >= 57, len(rows)
    wrong = [
        (r["entry"]["id"], r["entry"]["status"], r["rebuilt"])
        for r in rows
        if r["entry"]["status"] != r["rebuilt"]
    ]
    assert not wrong, wrong


def test_a_hand_raised_status_does_not_rebuild(tree):
    tree.edit("assurance/properties.toml", 'status = "MODELLED-ONLY"', 'status = "BOUNDED"')
    assert only(tree.problems(), "does not rebuild from the vector")


def test_a_hand_lowered_status_does_not_rebuild(tree):
    tree.edit("assurance/properties.toml", 'status = "BOUNDED"', 'status = "MODELLED-ONLY"')
    assert only(tree.problems(), "does not rebuild from the vector")


def test_a_risk_a_configuration_checks_does_not_rebuild(tree):
    """The third arm: a risk is exactly a row no configuration checks."""
    tree.edit("formal/Shipped.cfg", "    BarNeverOpens\n", "    BarNeverOpens\n    RuledAwayRisk\n")
    assert only(tree.problems(), "SEC-R-001")


def test_deleting_the_only_harness_moves_the_word(tree):
    """The `BOUNDED` half of the reconstruction is a Kani harness, not a wish."""
    tree.edit("crates/rsk-a/src/kani.rs", "foo_stays_closed_probe", "unrelated_probe")
    assert tree.vector("SEC-T-001")["kani"] == 0
    assert only(tree.problems(), "does not rebuild from the vector")


# --- the registry's hand-written field set is closed --------------------------


def test_a_hand_written_evidence_column_is_refused(tree):
    tree.append("assurance/properties.toml", "\n[[property]]\n"
                'id = "SEC-T-003"\nname = "Extra"\nstatus = "MODELLED-ONLY"\n'
                'statement = "s"\nsource = ["spec"]\nkani = 4\n')
    assert only(tree.problems(), "`kani` is a hand-written column")


def test_a_hand_written_hardware_column_is_refused(tree):
    tree.append("assurance/properties.toml", 'hardware = "verified on a board"\n')
    assert only(tree.problems(), "`hardware` is a hand-written column")


def test_a_hand_written_top_level_table_is_refused(tree):
    tree.append("assurance/properties.toml", '\n[hardware]\nboard = "RP2350 A2"\n')
    assert only(tree.problems(), "top-level `hardware` is a hand-written column")


def test_all_seven_written_fields_are_accepted(tree):
    """The other direction: a rule that refuses the fields in use is not a rule."""
    tree.edit("assurance/properties.toml", 'ruling = "the maintainer said so, dated"',
              'ruling = "the maintainer said so, dated"\nclause_of = "SEC-T-001"')
    tree.regenerate()
    assert tree.problems() == []


# --- a hardware claim names the board -----------------------------------------


def test_a_hardware_subject_without_a_board_revision(tree):
    tree.write("assurance/bundle/SEC-T-001.toml",
               tree.bundle(subjects='["abstract model", "hardware"]'))
    assert only(tree.problems(), "records no `build.board_revision`")


def test_a_measurement_method_without_a_board_revision(tree):
    """The second spelling. Closing one of two is how five guards here shipped."""
    tree.write("assurance/bundle/SEC-T-001.toml", tree.bundle(method="measurement"))
    assert only(tree.problems(), "records no `build.board_revision`")


def test_the_subject_is_read_case_and_space_insensitively(tree):
    tree.write("assurance/bundle/SEC-T-001.toml",
               tree.bundle(subjects='["abstract model", " Hardware "]'))
    assert only(tree.problems(), "records no `build.board_revision`")


def test_hardware_with_a_board_revision_is_evidence(tree):
    tree.write("assurance/bundle/SEC-T-001.toml",
               tree.bundle(subjects='["hardware"]', extra_build='board_revision = "RP2350 A2"\n'))
    tree.regenerate()
    assert tree.problems() == []
    assert tree.vector("SEC-T-001")["hardware"] == 1


def test_hardware_listed_as_absent_is_not_a_claim(tree):
    """`subjects_absent` names hardware in the tree's only bundle, deliberately.

    A rule matching the key by prefix would redden the honest case for being
    honest — which is the direction that makes a guard get deleted.
    """
    assert "hardware" in tree.bundle()  # via subjects_absent, as the real one has it
    assert tree.problems() == []
    assert tree.vector("SEC-T-001")["hardware"] == 0


# --- the trace handshake, in the spelling that was measured wrong -------------


def test_a_script_named_elsewhere_in_check_sh_is_not_wired_to_a_session(tree):
    """The 92-versus-11 trap, as a case.

    `other_gate.py` has a row of its own that names no session, and a different
    row names one. Reading `check.sh` whole rather than per row made every module
    naming any wired-up script a replay module.
    """
    tree.edit("formal/Mini.tla", "TypeOK == TRUE",
              "(* Derived by scripts/other_gate.py. *)\nTypeOK == TRUE")
    assert set(evidence_gate.trace_data_modules(tree.root)) == {"ReplayData"}
    assert tree.vector("SEC-T-001")["trace"] == 0


def test_a_commented_out_row_wires_nothing(tree):
    tree.edit("scripts/check.sh", 'run "replay data"', '# run "replay data"')
    assert evidence_gate.trace_data_modules(tree.root) == {}
    assert only(tree.problems(), "session.jsonl is replayed by no formal/ module")


def test_the_generator_may_name_the_session_itself(tree):
    """`trace_map.py`'s spelling: the script carries the path, no row needed."""
    tree.edit("scripts/check.sh",
              'run "replay data" python scripts/replay_gen.py formal/traces/session.jsonl',
              'run "replay data" python scripts/replay_gen.py')
    tree.append("scripts/replay_gen.py", 'TRACE = "formal/traces/session.jsonl"\n')
    assert set(evidence_gate.trace_data_modules(tree.root)) == {"ReplayData"}
    assert tree.problems() == []


def test_a_module_that_names_no_generator_is_not_a_replay_module(tree):
    tree.edit("formal/ReplayData.tla",
              "(* Generated by scripts/replay_gen.py from a recorded session. *)\n", "")
    assert only(tree.problems(), "session.jsonl is replayed by no formal/ module")


# --- an axis whose reader stopped reading the tree ----------------------------


def test_a_replaying_module_that_reaches_no_configuration(tree):
    """A module replays and no configuration is owned by it: the axis is dead."""
    for cfg in ("formal/Replay.cfg", "formal/ReplayBad.cfg"):
        tree.edit(cfg, "SPECIFICATION TraceSpec", "SPECIFICATION Spec")
    assert only(tree.problems(), "not one property carries trace evidence")


def test_comutants_that_resolve_to_no_invariant(tree):
    (tree.root / "formal/Solo_BugFooOpens.cfg").unlink()
    assert only(tree.problems(), "the invariant lookup stopped resolving")


def test_a_ledger_that_disposes_of_no_registry_id(tree):
    tree.write("assurance/configurations.toml",
               CONFIGURATIONS.replace("SEC-T-00", "SEC-GONE-00"))
    assert only(tree.problems(), "disposes of no property in the registry")


def test_a_tree_with_no_recorded_session_is_a_fact_not_a_finding(tree):
    """The floors are about a reader going blind, never about an empty tree."""
    (tree.root / "formal/traces/session.jsonl").unlink()
    tree.regenerate()
    assert only(tree.problems(), "recorded session") == []
    assert tree.vector("SEC-T-002")["trace"] == 0


# --- freshness ----------------------------------------------------------------


def test_an_input_committed_after_the_bundle_goes_stale(tree):
    """Stage 1B's "a security owner change marks dependent evidence stale"."""
    tree.append("crates/rsk-a/src/lib.rs", "// a later edit to the owner\n")
    tree.commit("touch the owner after the evidence was taken")
    vector = tree.vector("SEC-T-001")
    assert vector["freshness"] == "stale"
    assert "crates/rsk-a/src/lib.rs" in vector["behind"]
    assert "stale" in evidence_gate.render(tree.root)


def test_a_stale_bundle_rewrites_the_public_page(tree):
    """The claim weakens itself: the page no longer matches until it is rewritten."""
    tree.append("formal/Mini.tla", "\n(* a later edit to the model *)\n")
    tree.commit("touch the model after the evidence was taken")
    assert only(tree.problems(), "is not what the generator writes")
    tree.regenerate()
    assert tree.problems() == []


def test_a_bundle_commit_this_history_does_not_have(tree):
    tree.write("assurance/bundle/SEC-T-001.toml", tree.bundle(commit="0" * 40))
    assert only(tree.problems(), "which this history does not have")


def test_an_evidence_input_that_was_never_committed_is_not_covered(tree):
    tree.write("formal/Extra.cfg", SOLO_CFG)
    assert tree.vector("SEC-T-001")["freshness"] == "stale"


def test_a_bundle_with_no_commit_dates_nothing(tree):
    tree.write("assurance/bundle/SEC-T-001.toml",
               tree.bundle().replace(f'commit = "{tree.head()}"', 'commit = ""'))
    assert only(tree.problems(), "records no build commit")


def test_two_bundles_for_one_property(tree):
    tree.write("assurance/bundle/SEC-T-001-again.toml", tree.bundle())
    assert only(tree.problems(), "a second bundle for SEC-T-001")


# --- the generated page --------------------------------------------------------


def test_an_edited_page_is_refused(tree):
    tree.append("docs/assurance-vector.md", "\nand a sentence nobody derived\n")
    assert only(tree.problems(), "is not what the generator writes")


def test_a_missing_page_is_refused(tree):
    (tree.root / "docs/assurance-vector.md").unlink()
    assert only(tree.problems(), "is not what the generator writes")


def test_the_page_cannot_claim_more_than_the_axes(tree):
    """Delete the evidence and the sentence shrinks with it, on its own."""
    before = evidence_gate.render(tree.root)
    assert "**1 of 3** carry at least one Kani harness" in before
    tree.edit("crates/rsk-a/src/kani.rs", "foo_stays_closed_probe", "unrelated_probe")
    tree.edit("assurance/properties.toml", 'status = "BOUNDED"', 'status = "MODELLED-ONLY"')
    assert "**0 of 3** carry at least one Kani harness" in evidence_gate.render(tree.root)


def test_the_page_says_about_a_board_what_the_axis_says():
    """The one sentence a release note is most likely to get wrong.

    Held to the AXIS and not to the empty state, because the empty state stopped
    being this tree's: `PLAT-ROM-002` is discharged on a recorded stepping and
    the page prints the claim instead of the prohibition. A pin on "none" would
    have had to be DELETED for that to land, and a rule deleted to let a change
    through never fires again -- so what is pinned is that the page and the
    vectors point the same way, whichever way that is. The branch itself is
    driven both ways on the fixture, by the pending and the discharged silicon
    obligation below; this case is the reading of the real page.
    """
    page = (ROOT / evidence_gate.ARTIFACT).read_text()
    measured = [r for r in evidence_gate.vectors(ROOT, []) if r["vector"]["hardware"]]
    assert ("carry a result measured on a board" in page) == bool(measured), measured
    assert ("**no** row carries a hardware result" in page) == (not measured)


# --- the wiring ----------------------------------------------------------------


def test_check_sh_runs_this_gate():
    """The row's CODE: a `#` in front of it is not a row."""
    text = (ROOT / "scripts/check.sh").read_text()
    assert gate_lines.runs(text, "scripts/evidence_gate.py")


def test_the_page_is_listed_in_the_docs_nav():
    """A generated page mdBook never renders is one no reader ever sees."""
    assert "assurance-vector.md" in (ROOT / "docs/SUMMARY.md").read_text()


# --- naming an invariant is not asserting it ----------------------------------


def test_a_configuration_that_names_is_not_one_that_asserts(tree):
    """43 of the 46 naming `NoAuthorizationBypass` are mutants it must fall in."""
    tree.edit("formal/floors.txt", "Shipped.cfg     GREEN   1", "Shipped.cfg     RED     -")
    assert tree.vector("SEC-T-001")["asserted"] == 0
    assert tree.vector("SEC-T-001")["model"] == 2


def test_a_refused_session_is_not_accepted_evidence(tree):
    """`R4cGateAnswers` replays nine and two of them are runs where it holds."""
    assert (tree.vector("SEC-T-002")["trace"], tree.vector("SEC-T-002")["accepted"]) == (2, 1)
    tree.edit("formal/floors.txt", "Replay.cfg      GREEN   1", "Replay.cfg      RED     -")
    assert tree.vector("SEC-T-002")["accepted"] == 0
    assert tree.vector("SEC-T-002")["trace"] == 2


def test_a_verdict_registry_that_resolves_nothing(tree):
    tree.write("formal/floors.txt", "Nothing_*.cfg   GREEN   1\n")
    assert only(tree.problems(), "the verdict lookup stopped resolving")


def test_the_page_reports_both_halves(tree):
    page = evidence_gate.render(tree.root)
    assert "| 1 of 2 |" in page and "| 1 of 2 |" in page  # asserted of naming
    assert "ASSERTED by at least one finite TLA+ configuration" in page


# --- the third hardware spelling, and the inverse -----------------------------


def test_a_silicon_revision_named_anywhere_owes_the_board_field(tree):
    """`expires_on_stepping` is the bundle's own board-dependency field, and the
    first two rules walked straight past a stepping named in it."""
    tree.append("assurance/bundle/SEC-T-001.toml",
                '\n[freshness]\nexpires_on_stepping = "RP2350 A2 — every figure was taken on it"\n')
    assert only(tree.problems(), "names a silicon revision at")
    assert tree.vector("SEC-T-001")["hardware"] == 0


def test_the_bundle_may_say_a_stepping_change_expires_it(tree):
    """The honest case, which the tree's only bundle makes: the field names the
    TRIGGER and no revision, so it is not a claim."""
    tree.append("assurance/bundle/SEC-T-001.toml",
                '\n[freshness]\nexpires_on_stepping = "an RP2350 stepping change — nothing here"\n')
    tree.regenerate()
    assert tree.problems() == []


@pytest.mark.parametrize(
    "value",
    ["a red Pico 2 I had lying around", "the blue one on the desk", "rp2350 a2",
     "RP2350", "A2", "Pico 2 W", "B1",
     # And the desk with the part named INSIDE it, which is what a `search` over
     # an otherwise free field takes: all three published `1 of 3` at exit 0.
     "a red Pico 2 (an RP2350 A2) I had lying around",
     "not an RP2350 A2 at all",
     "RP2350 A2 and also RP2040"],
)
def test_a_board_revision_that_names_no_stepping(tree, value):
    """The measured hole: `platform_gate.py` held its own registry to this
    vocabulary and the bundle's declaration took any non-empty string, so a
    description of a desk published `1 of 59` carrying a board result."""
    tree.write("assurance/bundle/SEC-T-001.toml",
               tree.bundle(subjects='["hardware"]',
                           extra_build=f'board_revision = "{value}"\n'))
    assert only(tree.problems(), "names no RP2350 stepping"), value
    assert tree.vector("SEC-T-001")["hardware"] == 0, value


def test_the_two_registries_share_one_board_rule(tree):
    """The RULE, not the token — and this arm's own first version could not fail.

    It asserted `evidence_gate.BOARD_REVISION is platform_gate.BOARD_REVISION`,
    and `re` CACHES compiled patterns: `re.compile(t) is re.compile(t)` is True,
    so the copy-paste it was written against passed it. Driven — writing the
    forbidden `BOARD_REVISION = re.compile(r"\\bRP2350[\\s-]+A[0-9]\\b")` into
    `evidence_gate.py` left this case, both suites and the gate at EXIT=0.
    A function is not cached, so the same test over one holds.
    """
    assert evidence_gate.names_a_stepping is platform_gate.names_a_stepping


def test_a_board_revision_with_no_result_on_it(tree):
    """A board field nothing rests on, in both spellings of the value."""
    for value in ('RP2350 A2', 'A2'):
        tree.write("assurance/bundle/SEC-T-001.toml",
                   tree.bundle(extra_build=f'board_revision = "{value}"\n'))
        assert only(tree.problems(), "claims no result on it"), value
        assert tree.vector("SEC-T-001")["hardware"] == 0


# --- the half-stop the total floors could not see -----------------------------


def test_a_row_that_stopped_naming_its_session(tree):
    """Moving one row's session into a variable changes nothing about what runs.

    Measured on the real tree during review: `trace_data_modules` fell from 4 to
    2, four properties lost their trace evidence, and both total floors stayed
    silent while the page printed a smaller number.
    """
    tree.write("formal/traces/second.jsonl", '{"action": "Other"}\n')
    tree.append("scripts/check.sh",
                'run "second data" python scripts/other_gate.py formal/traces/second.jsonl\n')
    tree.append("formal/Mini.tla", "\n(* Generated by scripts/other_gate.py. *)\n")
    tree.regenerate()
    assert tree.problems() == []
    tree.edit("scripts/check.sh", "formal/traces/second.jsonl\n", '"$SESSION"\n')
    assert only(tree.problems(), "second.jsonl is replayed by no formal/ module")


# --- every derivation clause of the freshness input set -----------------------


def test_a_kani_harness_committed_after_the_bundle_goes_stale(tree):
    """The clause the first table could not fail: deleting it left 37 green."""
    tree.append("crates/rsk-a/src/kani.rs", "\n// a later edit to the harness\n")
    tree.commit("touch the harness after the evidence was taken")
    vector = tree.vector("SEC-T-001")
    assert vector["freshness"] == "stale"
    assert "crates/rsk-a/src/kani.rs" in vector["behind"]


def test_a_configuration_committed_after_the_bundle_goes_stale(tree):
    tree.append("formal/Shipped.cfg", "\n")
    tree.commit("touch a configuration after the evidence was taken")
    assert "formal/Shipped.cfg" in tree.vector("SEC-T-001")["behind"]


def test_a_re_recorded_run_after_the_bundle_goes_stale(tree):
    """The clause the tree demonstrated against the axis rather than for it.

    `982fb2f` touches `formal/runs.toml` and the generated pages and NO model,
    configuration or source, and it re-ran both tiers: a RED closing is where the
    run stopped, so `Mut_BugTokenlessIgnoresAlwaysUv.cfg` went 61236/10696 to
    59974/10559 across it — a line `SEC-FIDO-002` transcribes. Driven on the real
    history before the clause existed, a bundle dated at that commit's parent
    reported `fresh` over 45 derived inputs with every TLC number in the tree
    re-measured underneath it.
    """
    tree.append("formal/runs.toml", "\n# the tier re-run, model untouched\n")
    tree.commit("re-record the tier after the evidence was taken")
    vector = tree.vector("SEC-T-001")
    assert vector["freshness"] == "stale"
    assert "formal/runs.toml" in vector["behind"]


def test_a_property_no_configuration_checks_is_not_dated_against_the_record(tree):
    """The other half of that clause: it is conditioned, not blanket.

    A property no configuration checks transcribes no run, so the record is not a
    file its evidence is about — and an input on every property alike is the
    decoration this module refuses of a hand-written column.
    """
    checked = assurance_gate.checked_names(tree.root / "formal")
    assert "RuledAwayRisk" not in checked
    assert "formal/runs.toml" not in evidence_gate.evidence_inputs(
        tree.root, "RuledAwayRisk", "SEC-R-001", checked, None
    )
    assert "formal/runs.toml" in evidence_gate.evidence_inputs(
        tree.root, "FooStaysClosed", "SEC-T-001", checked, "Mini"
    )


def test_a_comutant_patch_target_committed_after_the_bundle_goes_stale(tree):
    """The bundle names seven co-refutation owners and the tag grep reaches two.

    Measured on the real tree: five of the seven carry no `Refines` tag, so a
    freshness axis built on the tag alone calls evidence fresh over an edit to
    the very code the kill was measured against.
    """
    assert "crates/rsk-a/src/twin.rs" in evidence_gate.comutant_patch_files(
        tree.root, "FooStaysClosed"
    )
    tree.append("crates/rsk-a/src/twin.rs", "// a later edit to the twin\n")
    tree.commit("touch the co-refutation target after the evidence was taken")
    assert "crates/rsk-a/src/twin.rs" in tree.vector("SEC-T-001")["behind"]


def test_a_module_the_model_extends_is_an_evidence_input(tree):
    """`TraceSecurity` EXTENDS `TraceSecurityData`; a model's parents are its own."""
    inputs = evidence_gate.evidence_inputs(
        tree.root, "BarNeverOpens", "SEC-T-002",
        {"BarNeverOpens": ["Shipped.cfg", "Replay.cfg", "ReplayBad.cfg"]}, "Replay",
    )
    assert "formal/ReplayData.tla" in inputs and "formal/Mini.tla" in inputs


def test_a_bundle_with_no_property_id_names_nothing(tree):
    tree.write("assurance/bundle/nameless.toml",
               tree.bundle().replace('id = "SEC-T-001"', 'invariant = "FooStaysClosed"'))
    assert only(tree.problems(), "a bundle with no property id")


# --- the degeneracy, recorded rather than asserted away -----------------------


def test_the_round_trips_disagreement_set_is_empty(tree):
    """§4.3 condition 11: on which inputs does the oracle DISAGREE? None.

    `reconstruct` reads the two derivations `assurance_gate.py` forces the word
    from, so every state it fires in is one that gate already refuses. Recorded
    as a case rather than argued in a docstring, because the value of the round
    trip is exactly this: the scalar carries no information of its own.
    """
    rows = evidence_gate.vectors(ROOT, [])
    forced = []
    for row in rows:
        vector = row["vector"]
        ceiling = (
            "ACCEPTED-RISK" if not vector["model"]
            else "BOUNDED" if vector["kani"] else "MODELLED-ONLY"
        )
        forced.append(ceiling == row["rebuilt"])
    assert all(forced), "reconstruct and the ceiling rule are one function"
    assert len(rows) >= 57


def test_the_prohibition_does_not_invert_when_the_axis_moves(tree):
    """A "may not say" bullet templated with its own count becomes the claim."""
    assert "no** row carries a hardware result" in evidence_gate.render(tree.root)
    tree.write("assurance/bundle/SEC-T-001.toml",
               tree.bundle(subjects='["hardware"]',
                           extra_build='board_revision = "RP2350 A2"\n'))
    page = evidence_gate.render(tree.root)
    assert "carry a result measured on a board" in page
    assert "row carries a hardware result" not in page


def test_the_axis_paragraph_prints_the_axis_and_not_a_literal(tree):
    """The SECOND copy of that sentence, which the case above could not see.

    `render`'s "The axes" prose carried the same claim as a hard-coded literal —
    "both give 0 … every obligation there is `pending`" — so the page went on
    refusing a board result through the commit that recorded two, and `--write`
    reproduced the refusal byte for byte, which left the page's own diff gate
    blind to it. Pinned to the AXIS and not to a wording, and driven both ways:
    the fixture registry is all-`pending`, and the same tree with its obligation
    discharged on a stepping must print the other number.
    """
    def printed(root):
        assurance_gate.co_refuted.cache_clear()
        page = evidence_gate.render(root)
        found = re.search(r"`hardware` reads two sources[^\n]*?\*\*(\d+) of (\d+)\*\*", page)
        assert found, "the axes prose prints no count off the hardware axis"
        return int(found.group(1)), int(found.group(2))

    def axis(root):
        assurance_gate.co_refuted.cache_clear()
        rows = evidence_gate.vectors(root, [])
        return sum(1 for row in rows if row["vector"]["hardware"]), len(rows)

    assert axis(tree.root)[0] == 0, "the fixture registry is meant to be all-pending"
    assert printed(tree.root) == axis(tree.root), "with the axis at 0"

    tree.edit("assurance/platform.toml", 'status = "pending"',
              'status = "discharged"\nboard_revision = "RP2350 A2"\n'
              'evidence = ["assurance/properties.toml"]\n'
              'revalidated_by = "a new stepping"')
    assert axis(tree.root)[0] == 1, "the discharged obligation did not move the axis"
    assert printed(tree.root) == axis(tree.root), "with the axis moved"


# --- the hardware axis's other source -----------------------------------------


def test_a_pending_platform_obligation_is_not_a_board_result(tree):
    """The state the real tree is in: an obligation with an owner, measured by
    nobody. Counting it would be the axis inventing the number it exists for."""
    assert tree.vector("SEC-T-001")["hardware"] == 0
    assert "no** row carries a hardware result" in evidence_gate.render(tree.root)


def test_a_discharged_silicon_obligation_is_a_board_result(tree):
    """And the axis moves — which is what stops the page printing the prohibition
    over a measurement that landed in the registry rather than in a bundle."""
    tree.edit("assurance/platform.toml", 'status = "pending"',
              'status = "discharged"\nboard_revision = "RP2350 A2"\n'
              'evidence = ["assurance/properties.toml"]\n'
              'revalidated_by = "a new stepping"')
    assert tree.vector("SEC-T-001")["hardware"] == 1
    page = evidence_gate.render(tree.root)
    assert "carry a result measured on a board" in page
    assert "row carries a hardware result" not in page


def test_a_discharged_obligation_with_no_stepping_is_not_a_board_result(tree):
    """`platform_gate.py` reddens this; the axis must not count it meanwhile."""
    tree.edit("assurance/platform.toml", 'status = "pending"',
              'status = "discharged"\nevidence = ["assurance/properties.toml"]\n'
              'revalidated_by = "a new stepping"')
    assert tree.vector("SEC-T-001")["hardware"] == 0


def test_a_board_result_counts_whatever_class_it_is_filed_under(tree):
    """The class sorts rows for a reader; it does not decide what a measurement
    is. Keying the axis on the silicon classes was the first version, and the
    review discharged the `tool-fidelity` row — whose own route reads "a board
    recording of the same session" — and got 0 over ten properties."""
    tree.edit("assurance/platform.toml", 'class = "flash"', 'class = "tool-fidelity"')
    tree.edit("assurance/platform.toml", 'status = "pending"',
              'status = "discharged"\nboard_revision = "RP2350 A2"\n'
              'evidence = ["assurance/properties.toml"]\n'
              'revalidated_by = "a new stepping"')
    assert tree.vector("SEC-T-001")["hardware"] == 1


def test_a_platform_registry_this_cannot_read_is_a_finding(tree):
    """The floor is on ENTRIES READ, not on properties backed: all-pending is a
    fact about the tree, and a registry resolving to nothing is a stopped reader."""
    tree.write("assurance/platform.toml", "# no entries\n")
    assert only(tree.problems(), "resolved no entry from it")


def test_both_sources_of_the_axis_add(tree):
    """A bundle declaration and a registry discharge are two results, not one."""
    tree.edit("assurance/platform.toml", 'status = "pending"',
              'status = "discharged"\nboard_revision = "RP2350 A2"\n'
              'evidence = ["assurance/properties.toml"]\n'
              'revalidated_by = "a new stepping"')
    tree.write("assurance/bundle/SEC-T-001.toml",
               tree.bundle(subjects='["hardware"]', extra_build='board_revision = "RP2350 A2"\n'))
    assert tree.vector("SEC-T-001")["hardware"] == 2


# --- the three outputs 1B asks for and the tree did not have ------------------


def test_the_rollup_covers_every_built_image_the_matrix_names():
    """The column list is `matrix_gate`'s, so the page cannot answer "how many
    built images are there" differently from the gate that owns the question."""
    import matrix_gate

    rows = evidence_gate.vectors(ROOT, [])
    named = {c.name for c in matrix_gate.columns(ROOT, matrix_gate.workspace(ROOT))}
    assert {n for n, _k, _p, _pl, _u in evidence_gate.per_column(ROOT, rows)} == named


def test_every_column_accounts_for_every_ledger_row():
    """`placed + unplaced` is the denominator, and a rollup that loses rows is how
    a gap stops being visible."""
    rows = evidence_gate.vectors(ROOT, [])
    ids = {r["entry"]["id"] for r in rows} & set(evidence_gate.scope_of(ROOT))
    for name, _kind, _pub, placed, unplaced in evidence_gate.per_column(ROOT, rows):
        assert placed + unplaced == len(ids), name


def test_the_feature_columns_are_the_point_of_the_rollup():
    """Roadmap §12 calls it feature blindness: a default-build proof is not a
    proof about the image a feature builds. The rollup must name that kind."""
    rows = evidence_gate.vectors(ROOT, [])
    kinds = {k for _n, k, _p, _pl, _u in evidence_gate.per_column(ROOT, rows)}
    assert {"package", "feature", "board"} <= kinds


def test_the_outstanding_list_reads_all_three_sources():
    """Bundle behind its inputs, property with no bundle, platform obligation
    pending. Reading one alone reports a clean tree over an unclean one."""
    rows = evidence_gate.vectors(ROOT, [])
    listed = evidence_gate.outstanding(ROOT, rows)
    kinds = {kind for kind, _s, _w in listed}
    assert "platform" in kinds
    assert "bundle" in kinds
    assert any("no raw evidence bundle" in why for _k, _s, why in listed)


def test_the_review_packet_names_what_reproduces_each_artifact():
    made = evidence_gate.packet(ROOT, evidence_gate.vectors(ROOT, []))
    assert made["artifacts"] and made["runs"]
    assert all(command.startswith("python ") for _a, command in made["artifacts"])
    # And it names NO commit: a page that embeds the tree's head is stale the
    # moment it is committed, so the gate would redden on its own output. Measured
    # — that is exactly how this section failed its first full `check.sh`.
    assert "commit" not in made


def test_a_rollup_that_collapsed_is_a_finding_and_not_a_regenerated_blank(monkeypatch):
    """The failure a byte-diff cannot see: a section that empties still matches
    what the generator writes, because the generator writes the empty one."""
    rows = evidence_gate.vectors(ROOT, [])
    monkeypatch.setattr(evidence_gate, "per_column", lambda *a, **k: [])
    findings = []
    evidence_gate.check_rollups(ROOT, rows, findings)
    assert any("rollup is empty" in f for f in findings), findings


def test_an_outstanding_list_that_stopped_reading_a_source_is_a_finding(monkeypatch):
    rows = evidence_gate.vectors(ROOT, [])
    monkeypatch.setattr(evidence_gate, "outstanding", lambda *a, **k: [])
    findings = []
    evidence_gate.check_rollups(ROOT, rows, findings)
    assert any("no platform obligation" in f for f in findings), findings


def test_a_packet_that_lists_nothing_is_a_finding(monkeypatch):
    rows = evidence_gate.vectors(ROOT, [])
    monkeypatch.setattr(
        evidence_gate, "packet", lambda *a, **k: {"artifacts": [], "runs": [], "commit": "x", "bundles": [], "stale": [], "properties": 0}
    )
    findings = []
    evidence_gate.check_rollups(ROOT, rows, findings)
    assert any("reproduces nothing" in f for f in findings), findings


# --- the same pipe, one file over ---------------------------------------------


def outstanding_table(page):
    """The `Stale and pending` table as a renderer sees it: header, then rows."""
    lines = page.splitlines()
    head = next(i for i, line in enumerate(lines) if line.startswith("| Kind | Subject |"))
    rows = []
    for line in lines[head + 2:]:
        if not line.startswith("| "):
            break
        rows.append(P.UNESCAPED_PIPE.split(line)[1:-1])
    return P.UNESCAPED_PIPE.split(lines[head])[1:-1], rows


PENDING_STATEMENT = 'statement = "The tear model is the one the store assumes."'


def test_a_pipe_in_a_pending_statement_does_not_end_the_outstanding_row(tree):
    """This page publishes the SAME registry's prose, with no helper of its own.

    Green today only because no pending statement's first seventy characters
    carries a pipe — which is a fact about the registry's current text, not a
    rule, and the row that carried one four columns wide was `PLAT-SOURCE-002`.
    """
    tree.edit("assurance/platform.toml", PENDING_STATEMENT,
              f"statement = '{P.PIPED_DISCHARGE}'")
    tree.regenerate()
    header, rows = outstanding_table(evidence_gate.render(tree.root))
    assert rows, "the fixture rendered no outstanding rows"
    assert [len(row) for row in rows] == [len(header)] * len(rows)
    why = next(row for row in rows if "PLAT-FLASH-001" in row[1])[2].strip()
    assert why.replace("\\|", "|") == P.PIPED_DISCHARGE


def test_the_cut_lands_on_raw_prose_and_not_inside_an_escape(tree):
    """Seventy characters of the REGISTRY's text, not seventy of the escaped text.

    The other order — escape, then `[:70]` — leaves the row ending in half an
    escape: measured, a trailing lone backslash where the `\\|` was cut in two.
    """
    long = "x" * 69 + "| the rest of the sentence"
    tree.edit("assurance/platform.toml", PENDING_STATEMENT, f"statement = '{long}'")
    tree.regenerate()
    _header, rows = outstanding_table(evidence_gate.render(tree.root))
    why = next(row for row in rows if "PLAT-FLASH-001" in row[1])[2].strip()
    assert why.replace("\\|", "|") == long[:70]


@pytest.mark.parametrize("what", sorted(P.REFUSED))
def test_a_character_no_escape_reaches_refuses_this_page_too(tree, what):
    """A finding, not a traceback — and that is why the escape is at the EMIT.

    Measured with it at `outstanding`'s `[:70]` instead: `check_rollups` calls
    that function OUTSIDE `audit`'s try, so the `ValueError` left `audit` as an
    uncaught traceback rather than as this page's own named refusal.
    """
    tree.edit("assurance/platform.toml", PENDING_STATEMENT,
              f'statement = "{P.REFUSED[what]}"')
    assert only(tree.problems(), "cannot be generated")
