#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 RS-Key contributors
"""Map a recorded emulator session onto RSKeyAppletSeams actions — phase 4's seam.

`formal/record-seam-trace.py` writes wire-level events; this maps them onto the
model's action vocabulary and emits `formal/TraceSeamsData.tla`, the sequence
TLC then replays against the model (`TraceSeams.cfg`): every recorded session
must be a behavior the model admits, and a divergence is a deadlock at the
exact step.

The mapping is STRICT, which is most of its value. An event outside the mapped
vocabulary, a status word that is neither success nor a retry count, a verify
on an applet the tracker says is not selected — each is a hard error, never a
silent stutter, because a mapper that skips what it does not understand is a
checker that stopped checking. The one piece of state the mapper keeps is the
current selection: the wire says only "SELECT piv", and whether that is the
model's `Reselect` or `SelectOther` depends on what was selected before — the
same `reselect` flag the Dispatcher computes (crates/rsk-sdk/src/applet.rs:379).

The default mode is the gate's: re-map the committed trace and hold the result
against the committed `TraceSeamsData.tla`, so the two cannot drift apart
silently (`--write` regenerates instead). The TLC half of the pipeline carries
its own falsifiability: `TraceSeamsBad.cfg` replays a hand-written trace the
model must refuse, and `floors.txt` requires that row RED.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
TRACE = ROOT / "formal" / "traces" / "seams-session.jsonl"
DATA = ROOT / "formal" / "TraceSeamsData.tla"

#: The wire applet names, in the model's vocabulary (RSKeyAppletSeams Applets).
APPS = {"piv", "pgp", "oath"}

#: Which verify events map to which model action. OATH is absent on purpose:
#: its VALIDATE is a challenge-response and its OTP-PIN carries store state the
#: session does not provision, so the recorder does not speak them yet.
VERIFY_ACTION = {
    ("piv", "pivPin"): "PivVerify",
    ("pgp", "pw1"): "PgpVerify",
    ("pgp", "pw2"): "PgpVerify",
    ("pgp", "pw3"): "PgpVerify",
}

HEADER = """---- MODULE TraceSeamsData ----
(*****************************************************************************)
(* SPDX-License-Identifier: AGPL-3.0-only                                    *)
(* Copyright (C) 2026 RS-Key contributors                                    *)
(*                                                                           *)
(* GENERATED by scripts/trace_map.py from formal/traces/seams-session.jsonl  *)
(* -- do not edit by hand; `python3 scripts/trace_map.py --write` remaps.    *)
(*****************************************************************************)
"""

FOOTER = "====\n"


def sw_ok(sw: str, where: str, problems: list[str]) -> bool | None:
    """9000 -> True, 63Cx -> False, anything else -> a problem (strict)."""
    if sw == "9000":
        return True
    if sw.startswith("63C") and len(sw) == 4:
        return False
    problems.append(f"{where}: status word {sw} is neither success nor a retry count")
    return None


def map_events(events: list[dict]) -> tuple[list[str], list[str]]:
    """(TLA+ record literals, problems). Tracks the selection like the Dispatcher."""
    out: list[str] = []
    problems: list[str] = []
    sel: str | None = None
    for i, e in enumerate(events, 1):
        where = f"event {i} ({e.get('ev', '?')})"
        kind = e.get("ev")
        if kind == "select":
            app = e.get("app")
            if app not in APPS:
                problems.append(f"{where}: unknown applet {app!r}")
                continue
            if e.get("sw") != "9000":
                problems.append(f"{where}: a refused SELECT has no model action")
                continue
            act = "Reselect" if sel == app else "SelectOther"
            out.append(f'[act |-> "{act}", a |-> "{app}"]')
            sel = app
        elif kind == "verify":
            app, ref = e.get("app"), e.get("ref")
            action = VERIFY_ACTION.get((app, ref))
            if action is None:
                problems.append(f"{where}: no mapping for ({app}, {ref})")
                continue
            if sel != app:
                problems.append(
                    f"{where}: verify on {app} while the tracker says {sel!r} is selected"
                )
                continue
            ok = sw_ok(e.get("sw", ""), where, problems)
            if ok is None:
                continue
            flag = "TRUE" if ok else "FALSE"
            if action == "PivVerify":
                out.append(f'[act |-> "PivVerify", ok |-> {flag}]')
            else:
                out.append(f'[act |-> "PgpVerify", r |-> "{ref}", ok |-> {flag}]')
        elif kind == "card_reset":
            out.append('[act |-> "CardReset"]')
            sel = None
        elif kind == "power_cycle":
            out.append('[act |-> "PowerCycle"]')
            sel = None
        else:
            problems.append(f"{where}: unknown event kind {kind!r}")
    return out, problems


def render(records: list[str]) -> str:
    body = ",\n    ".join(records)
    return f"{HEADER}\nTrace == <<\n    {body}\n>>\n\n{FOOTER}"


def load_events(path: pathlib.Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def audit(root):
    """(problems, one-line summary) — the committed map is in sync and mappable."""
    root = pathlib.Path(root)
    trace = root / "formal" / "traces" / "seams-session.jsonl"
    data = root / "formal" / "TraceSeamsData.tla"
    problems: list[str] = []
    if not trace.is_file():
        return [f"{trace.relative_to(root)} is missing"], ""
    records, map_problems = map_events(load_events(trace))
    problems += map_problems
    if not records:
        problems.append("the trace mapped to zero actions — nothing would be checked")
    if not data.is_file():
        problems.append(f"{data.relative_to(root)} is missing — run --write")
    elif not problems and data.read_text() != render(records):
        problems.append(
            "TraceSeamsData.tla does not match the mapping of the committed trace — "
            "one of the two changed without the other; run scripts/trace_map.py --write"
        )
    return problems, f"trace-map: ok — {len(records)} actions from {trace.name}"


def main():
    if sys.argv[1:] == ["--write"]:
        records, problems = map_events(load_events(TRACE))
        if problems:
            for p in problems:
                print(f"  {p}", file=sys.stderr)
            return 1
        DATA.write_text(render(records))
        print(f"wrote {DATA.relative_to(ROOT)} ({len(records)} actions)")
        return 0
    problems, summary = audit(ROOT)
    if problems:
        print("trace-map:", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 1
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
